(function(){"use strict";const api=window.DinPulsEmergency;if(!api)return;const $=s=>document.querySelector(s),statusLabel={permanent:"Permanent funktion",planned:"Planerad – inte aktiv",activated_when_needed:"Aktiveras vid behov",active_now:"Aktiv nu"},typeLabel={information_point:"Informationspunkt",safety_point:"Trygghetspunkt",emergency_water:"Nödvatten",other:"Annan funktion"};const tel=n=>n.replace(/\s/g,"");
function source(url,label="Primärkälla"){return `<a href="${api.escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${api.escapeHtml(label)} <span aria-hidden="true">↗</span></a>`}
async function init(){const name=api.municipality(),{national,local}=await api.load(),municipal=local.municipalities?.[name]||null;$("#emergency-place").textContent=name;document.querySelectorAll("[data-emergency-municipality]").forEach(x=>x.textContent=name);$("#emergency-home-link-page").href=`index.html?kommun=${encodeURIComponent(name)}`;document.title=`Kris & beredskap i ${name} | DinPuls`;
$("#emergency-numbers").innerHTML=national.numbers.map(x=>`<a href="tel:${tel(x.number)}" aria-label="Ring ${api.escapeHtml(x.number)}, ${api.escapeHtml(x.label)}"><strong>${api.escapeHtml(x.number)}</strong><span>${api.escapeHtml(x.label)}</span></a>`).join("");
$("#emergency-radio").innerHTML=municipal?`<div><span>DIN BEREDSKAPSKANAL</span><strong>${api.escapeHtml(municipal.radio.channel)}</strong><b>${api.escapeHtml(municipal.radio.frequency)}</b><small>${api.escapeHtml(municipal.radio.transmitter)}</small></div><p>Sveriges Radio P4 förmedlar viktig lokal information vid samhällsstörningar.</p>${source(municipal.radio.primaryUrl,municipal.radio.sourceName)}`:`<div><span>DIN BEREDSKAPSKANAL</span><strong>Sveriges Radio P4</strong><small>Kontrollera lokal kanal och frekvens hos Sveriges Radio.</small></div><p>P4 är Sveriges beredskapskanal. Lokal frekvens är ännu inte ansluten för ${api.escapeHtml(name)}.</p>`;
if(!municipal){$("#emergency-local-missing").hidden=false;$("#emergency-local-missing").innerHTML=`<h2>Lokal beredskapsinformation är ännu inte ansluten för ${api.escapeHtml(name)}</h2><p>Nationella nummer, råd, larmsignaler, skyddsrumskarta och hemberedskap visas fortsatt. Ingen lokal information från Åmål används som ersättning.</p>`;$("#trygghet").hidden=true}
$("#emergency-scenarios").innerHTML=national.scenarios.map(x=>`<details><summary>${api.escapeHtml(x.title)}</summary><p>${api.escapeHtml(x.body)}</p>${source(x.url)}</details>`).join("");
if(municipal){$("#emergency-places").innerHTML=municipal.places.map(x=>`<article class="emergency-place"><div><span>${api.escapeHtml(typeLabel[x.type]||x.type)}</span><b class="status-${api.escapeHtml(x.status)}">${api.escapeHtml(statusLabel[x.status]||x.status)}</b></div><h3>${api.escapeHtml(x.name)}</h3><p>${api.escapeHtml(x.address)}</p><p>${api.escapeHtml(x.description)}</p><strong>${api.escapeHtml(x.activationNote)}</strong>${source(x.primaryUrl,x.source)}</article>`).join("");const w=municipal.emergencyWater;$("#emergency-water").innerHTML=`<span>NÖDVATTEN · ${api.escapeHtml(statusLabel[w.status])}</span><h3>Nödvatten i Åmål</h3><p>${api.escapeHtml(w.text)}</p><ul>${w.locations.map(x=>`<li>${api.escapeHtml(x)}</li>`).join("")}</ul>${source(w.primaryUrl,w.sourceName)}`}
$("#emergency-shelter-principle").textContent=national.shelters.princip;$("#emergency-shelter-link").href=national.shelters.mapUrl;$("#emergency-shelter-local").textContent=municipal?.shelters.note||`Ingen lokal skyddsrumsstatistik är ansluten för ${name}. Använd den aktuella officiella kartan.`;
$("#emergency-alarms").innerHTML=national.alarms.map(x=>`<article><h3>${api.escapeHtml(x.name)}</h3><p><strong>Så låter den:</strong> ${api.escapeHtml(x.sound)}</p><p><strong>Gör så här:</strong> ${api.escapeHtml(x.action)}</p>${source(x.url)}</article>`).join("");const mobile=national.mobileWarning;$("#emergency-mobile-warning").innerHTML=`<span>VARNING VIA MOBIL</span><h3>${api.escapeHtml(mobile.name)}</h3><p>${api.escapeHtml(mobile.text)}</p>${source(mobile.url,mobile.sourceName)}`;
const key="dinpuls-emergency-checklist-v1";let saved={};try{saved=JSON.parse(localStorage.getItem(key)||"{}")||{}}catch{}const checklist=$("#emergency-checklist");checklist.innerHTML=national.preparedness.map(x=>`<label><input type="checkbox" data-check="${api.escapeHtml(x.id)}" ${saved[x.id]?"checked":""}><span><strong>${api.escapeHtml(x.label)}</strong><small>${api.escapeHtml(x.detail)}</small></span><b>${saved[x.id]?"Klart":"Inte klart"}</b></label>`).join("");checklist.addEventListener("change",e=>{const input=e.target.closest("[data-check]");if(!input)return;saved[input.dataset.check]=input.checked;localStorage.setItem(key,JSON.stringify(saved));input.closest("label").querySelector("b").textContent=input.checked?"Klart":"Inte klart"});$("#emergency-reset").addEventListener("click",()=>{if(!confirm("Vill du återställa hela checklistan?"))return;localStorage.removeItem(key);checklist.querySelectorAll("input").forEach(x=>{x.checked=false;x.closest("label").querySelector("b").textContent="Inte klart"})});
const b=national.brochure;$("#emergency-brochure").innerHTML=`<h3>${api.escapeHtml(b.title)}</h3><p>Läs den senaste officiella broschyren eller välj ljud, andra språk och teckenspråk.</p><div>${source(b.mainUrl,"Läs eller beställ")} ${source(b.audioUrl,"Lyssna")} ${source(b.languagesUrl,"Andra språk")} ${source(b.signLanguageUrl,"Teckenspråk")}</div>`;$("#emergency-war-brochure").href=b.mainUrl;
const info=municipal?`<dl><div><dt>Kommun</dt><dd>${api.escapeHtml(name)}</dd></div><div><dt>Beredskapskanal</dt><dd>${api.escapeHtml(municipal.radio.channel)}</dd></div><div><dt>Frekvens</dt><dd>${api.escapeHtml(municipal.radio.frequency)}</dd></div><div><dt>Viktiga nummer</dt><dd>112 · 113 13 · 1177 · 114 14</dd></div><div><dt>Informationspunkt</dt><dd>${api.escapeHtml(municipal.places[0].name)}, ${api.escapeHtml(municipal.places[0].address)} – aktiveras vid behov</dd></div></dl>`:`<dl><div><dt>Kommun</dt><dd>${api.escapeHtml(name)}</dd></div><div><dt>Beredskapskanal</dt><dd>Sveriges Radio P4</dd></div><div><dt>Viktiga nummer</dt><dd>112 · 113 13 · 1177 · 114 14</dd></div></dl>`;$("#emergency-card-fixed").innerHTML=info;$("#emergency-print").addEventListener("click",()=>window.print());window.lucide?.createIcons()}
init().catch(()=>{$("#emergency-local-missing").hidden=false;$("#emergency-local-missing").textContent="Krisinformationen kunde inte hämtas just nu."});})();


