(async function(){"use strict";
const api=window.DinPulsFamily,esc=api.escapeHtml,name=api.municipality(),section=document.querySelector("#family-section"),select=document.querySelector("#family-category"),cards=document.querySelector("#family-place-list"),count=document.querySelector("#family-result-count"),empty=document.querySelector("#family-empty"),mapHost=document.querySelector("#family-map");
document.querySelector("#family-place").textContent=name;let payload,item;try{payload=await api.load();item=payload.municipalities?.[name]||null}catch{section.dataset.state="error";empty.hidden=false;empty.textContent="Familjeplatserna kunde inte hämtas just nu.";return}
const categories=payload.categories||[],labels=new Map(categories.map(category=>[category.id,category.label]));select.add(new Option("Visa allt","all"));categories.forEach(category=>select.add(new Option(category.label,category.id)));
if(!item?.places?.length){section.dataset.state="empty";select.disabled=true;mapHost.hidden=true;empty.hidden=false;empty.textContent=`Inga verifierade familjeplatser är publicerade för ${name} ännu.`;count.textContent="0 platser";return}
let map=null,markers=new Map(),activeId=null;
if(window.L){map=L.map(mapHost,{scrollWheelZoom:false}).setView([item.mapCenter.latitude,item.mapCenter.longitude],item.mapCenter.zoom||13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map)}else{mapHost.innerHTML='<p class="family-map-error">Kartan kunde inte startas. Platslistan fungerar fortfarande.</p>'}
const tagList=place=>place.categories.map(id=>`<span>${esc(labels.get(id)||id)}</span>`).join("");
const facts=place=>[["Plats",place.address],["Passar",place.ageSuitability],["Kostnad",place.cost],["Säsong",place.season],["Öppettider",place.openingHours],["Tillgänglighet",place.accessibility],["Barnvagn",place.strollerFriendly===true?"Ja":place.strollerFriendly===false?"Nej":null]].filter(([,value])=>value).map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join("");
const card=place=>`<article class="family-place-card" id="family-card-${esc(place.id)}" data-family-place="${esc(place.id)}"><div class="family-place-card-head"><div><h3>${esc(place.name)}</h3><div class="family-tags">${tagList(place)}</div></div><button type="button" data-focus-place="${esc(place.id)}">Visa på kartan</button></div><p>${esc(place.shortDescription)}</p><dl>${facts(place)}</dl>${place.facilities?.length?`<p class="family-facilities"><b>På plats:</b> ${esc(place.facilities.join(" · "))}</p>`:""}<div class="family-card-links"><a href="${esc(place.primaryUrl)}" target="_blank" rel="noopener noreferrer">Officiell information ↗</a><small>Verifierad ${esc(place.verifiedAt)}</small></div></article>`;
function focusPlace(id,fromMarker=false){activeId=id;document.querySelectorAll("[data-family-place]").forEach(node=>node.classList.toggle("is-selected",node.dataset.familyPlace===id));const place=item.places.find(entry=>entry.id===id),marker=markers.get(id);if(marker&&map){map.setView([place.coordinates.latitude,place.coordinates.longitude],Math.max(map.getZoom(),15),{animate:true});marker.openPopup()}if(fromMarker)document.querySelector(`#family-card-${CSS.escape(id)}`)?.scrollIntoView({behavior:"smooth",block:"nearest"})}
function render(){const filter=select.value,places=item.places.filter(place=>filter==="all"||place.categories.includes(filter));count.textContent=`${places.length} ${places.length===1?"plats":"platser"}`;cards.innerHTML=places.map(card).join("");empty.hidden=places.length>0;if(!places.length)empty.textContent="Inga verifierade platser finns i den valda kategorin.";markers.forEach(marker=>map?.removeLayer(marker));markers.clear();if(map&&places.length){const bounds=[];for(const place of places){const position=[place.coordinates.latitude,place.coordinates.longitude],marker=L.marker(position).addTo(map).bindPopup(`<b>${esc(place.name)}</b><br>${esc(place.shortDescription)}`);marker.on("click",()=>focusPlace(place.id,true));markers.set(place.id,marker);bounds.push(position)}if(places.length===1)map.setView(bounds[0],15);else map.fitBounds(bounds,{padding:[28,28],maxZoom:14})}if(activeId&&!places.some(place=>place.id===activeId))activeId=null;window.lucide?.createIcons()}
select.addEventListener("change",render);cards.addEventListener("click",event=>{const button=event.target.closest("[data-focus-place]");if(button)focusPlace(button.dataset.focusPlace)});render();
})();
