const params=new URLSearchParams(location.search),initialMunicipality=params.get("kommun")||"Åmål",initialAssociation=params.get("forening")||"";
const TOKEN_KEY="dp-association-session",slug=value=>String(value||"").toLocaleLowerCase("sv-SE").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
let apiBase="",catalog=[];
const withContext=(path,mode="")=>{const p=new URLSearchParams();if(mode)p.set("mode",mode);const municipality=document.querySelector("#associationMunicipality")?.value||initialMunicipality;if(municipality)p.set("kommun",municipality);if(initialAssociation)p.set("forening",initialAssociation);return path+(p.size?"?"+p:"")};
for(const id of ["accountBack","infoLink"]){const el=document.getElementById(id);if(el)el.href=withContext("foreningar-konto.html")}
const card=document.getElementById("associationAuthCard"),login=document.getElementById("associationLogin"),registration=document.getElementById("associationRegistration"),activation=document.getElementById("associationActivation");
function showRegister(){card.hidden=false;activation.hidden=true;card.classList.add("is-flipped");login.setAttribute("aria-hidden","true");login.inert=true;registration.removeAttribute("aria-hidden");registration.inert=false;history.replaceState(null,"",withContext("foreningskonto.html","register"))}
function showLogin(){card.hidden=false;activation.hidden=true;card.classList.remove("is-flipped");registration.setAttribute("aria-hidden","true");registration.inert=true;login.removeAttribute("aria-hidden");login.inert=false;history.replaceState(null,"",withContext("foreningskonto.html"))}
document.getElementById("showAssociationRegistration")?.addEventListener("click",showRegister);document.getElementById("showAssociationLogin")?.addEventListener("click",showLogin);if(params.get("mode")==="register")showRegister();
async function api(path,options={}){const response=await fetch(apiBase+path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})},cache:"no-store"}),data=await response.json().catch(()=>({ok:false,error:"Servern gav ett ogiltigt svar."}));if(!response.ok)throw new Error(data.error||"Åtgärden misslyckades.");return data}
function normalize(raw,municipality){const all=[...(raw.sports?.municipalities?.[municipality]?.clubs||[]),...(raw.leisure?.municipalities?.[municipality]?.activities||[])],seen=new Map;for(const item of all){const name=item.name||item.club;if(!name)continue;const key=slug(name);if(!seen.has(key))seen.set(key,{slug:key,name})}return [...seen.values()].sort((a,b)=>a.name.localeCompare(b.name,"sv"))}
function renderAssociations(){const municipality=document.querySelector("#associationMunicipality").value;catalog=normalize(window.associationRaw,municipality);document.querySelector("#associationOptions").replaceChildren(...catalog.map(item=>{const option=document.createElement("option");option.value=item.name;return option}));const selected=catalog.find(item=>item.slug===initialAssociation);if(selected)document.querySelector("#associationSearch").value=selected.name}
async function setup(){try{const [config,municipalities,sports,leisure]=await Promise.all([fetch("data/business-config.json",{cache:"no-store"}).then(r=>r.json()),fetch("data/municipalities.json",{cache:"no-store"}).then(r=>r.json()),fetch("data/sports.json",{cache:"no-store"}).then(r=>r.json()),fetch("data/leisure.json",{cache:"no-store"}).then(r=>r.json())]);apiBase=String(config.apiBase||"").replace(/\/$/,"");if(!apiBase)throw new Error("Föreningstjänsten saknas.");window.associationRaw={sports,leisure};const municipalitySelect=document.querySelector("#associationMunicipality");municipalitySelect.replaceChildren(...municipalities.municipalities.map(item=>new Option(item.name,item.name)));municipalitySelect.value=municipalities.municipalities.some(item=>item.name===initialMunicipality)?initialMunicipality:"Åmål";municipalitySelect.onchange=()=>{document.querySelector("#associationSearch").value="";renderAssociations()};renderAssociations();const hash=new URLSearchParams(location.hash.slice(1)),token=hash.get("token"),purpose=hash.get("purpose");if(token&&["activate-association","reset-association-password"].includes(purpose)){card.hidden=true;activation.hidden=false;const reset=purpose==="reset-association-password",status=document.getElementById("associationActivationStatus"),form=document.getElementById("associationActivationForm");document.getElementById("associationActivationTitle").textContent=reset?"Återställ lösenord":"Skapa ditt lösenord";try{const result=await api(reset?"/portal/association/reset/verify":"/portal/association/token/verify",{method:"POST",body:JSON.stringify({token})});status.textContent=(reset?"Välj ett nytt lösenord.":"Aktivera kontot för "+result.associationName+".")+" Lösenordet ska ha minst 12 tecken, stor och liten bokstav samt en siffra.";form.hidden=false;form.onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form)),message=form.querySelector(".form-message");try{const done=await api(reset?"/portal/association/reset/complete":"/portal/association/password",{method:"POST",body:JSON.stringify({token,...values})});message.hidden=false;message.textContent=done.message;form.querySelector("button").disabled=true;history.replaceState(null,"",withContext("foreningskonto.html"))}catch(error){message.hidden=false;message.textContent=error.message}}}catch(error){status.textContent=error.message}}}catch(error){document.querySelectorAll(".form-message").forEach(message=>{message.hidden=false;message.textContent=error.message})}}
document.getElementById("associationRegistrationForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form)),message=form.querySelector(".form-message"),button=form.querySelector("button"),selected=catalog.find(item=>item.name===values.association);if(!selected){message.hidden=false;message.textContent="Välj en förening ur listan. Hittar du inte föreningen använder du kontaktlänken.";return}button.disabled=true;try{const result=await api("/portal/association/register",{method:"POST",body:JSON.stringify({municipality:values.municipality,associationSlug:selected.slug,contactName:values.name,statedRole:values.role,email:values.email,phone:values.phone})});message.hidden=false;message.textContent=result.message;form.reset();document.querySelector("#associationMunicipality").value=values.municipality;renderAssociations()}catch(error){message.hidden=false;message.textContent=error.message}finally{button.disabled=false}});
document.getElementById("associationLoginForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form)),message=form.querySelector(".form-message");try{const result=await api("/portal/auth/association",{method:"POST",body:JSON.stringify(values)});sessionStorage.setItem(TOKEN_KEY,result.token);location.href="foreningsadmin.html"}catch(error){message.hidden=false;message.textContent=error.message}});setup();
const loginForm=document.getElementById("associationLoginForm"),resetForm=document.getElementById("associationResetForm");document.getElementById("showAssociationReset").onclick=()=>{loginForm.hidden=true;resetForm.hidden=false};document.getElementById("cancelAssociationReset").onclick=()=>{resetForm.hidden=true;loginForm.hidden=false};resetForm.onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,message=form.querySelector(".form-message");try{const result=await api("/portal/association/reset/request",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(form)))});message.hidden=false;message.textContent=result.message}catch(error){message.hidden=false;message.textContent=error.message}};
setup();
