(function(){"use strict";
const api=window.DinPulsPractical;if(!api)return;const $=s=>document.querySelector(s);let map,layer,currentSide="map",flipCount=0,record;
const icons={map:"map-pinned",information:"notebook-tabs",hybrid:"map"};
function setSide(next){if(next===currentSide)return;currentSide=next;flipCount++;const card=$("#practical-flip");card.classList.toggle("is-flipped",next==="information");card.dataset.flipCount=String(flipCount);card.dataset.side=next;requestAnimationFrame(()=>map?.invalidateSize())}
function sourceLink(item){const url=item.externalUrl||item.primaryUrl||item.source?.url;return url?`<a class="practical-source-link" href="${api.escapeHtml(url)}" target="_blank" rel="noopener noreferrer">Läs mer hos ${api.escapeHtml(typeof item.source==="string"?item.source:item.source?.label||"primärkällan")} <span aria-hidden="true">↗</span></a>`:""}
function filteredPlaces(category){const settlement=$("#practical-settlement").value;return record.places.filter(p=>p.categories.includes(category.id)&&(settlement==="all"||p.settlement===settlement))}
function renderMap(category){setSide("map");const places=filteredPlaces(category),list=$("#practical-place-list"),count=$("#practical-result-count");count.textContent=`${places.length} ${places.length===1?"plats":"platser"}`;list.innerHTML=places.length?places.map((p,i)=>`<article class="practical-place"><div><span class="practical-index">${i+1}</span><h3>${api.escapeHtml(p.name)}</h3></div><p>${api.escapeHtml(p.address)}</p><p>${api.escapeHtml(p.description)}</p>${p.openingHours?`<p><strong>Öppettider:</strong> ${api.escapeHtml(p.openingHours)}</p>`:""}${p.facilities?.length?`<ul>${p.facilities.map(x=>`<li>${api.escapeHtml(x)}</li>`).join("")}</ul>`:""}<button type="button" data-place="${api.escapeHtml(p.id)}">Visa på kartan</button>${sourceLink(p)}</article>`).join(""):`<p class="practical-empty-inline">Inga verifierade platser i valt område. Välj Hela kommunen för att se samtliga.</p>`;
if(!map){map=L.map("practical-map",{scrollWheelZoom:false}).setView(record.mapCenter,11);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map)}if(layer)layer.remove();layer=L.featureGroup().addTo(map);const markers=new Map();places.forEach((p,i)=>{const marker=L.marker(p.coordinates).bindPopup(`<strong>${api.escapeHtml(p.name)}</strong><br>${api.escapeHtml(p.address)}`).addTo(layer);markers.set(p.id,marker)});if(places.length)map.fitBounds(layer.getBounds().pad(.18),{maxZoom:15});else map.setView(record.mapCenter,10);list.querySelectorAll("[data-place]").forEach(btn=>btn.addEventListener("click",()=>{const marker=markers.get(btn.dataset.place);if(marker){map.setView(marker.getLatLng(),16);marker.openPopup();$("#practical-map").focus()}}));
const hybrid=$("#practical-hybrid");const info=record.information.find(x=>x.category===category.id);hybrid.hidden=category.presentationType!=="hybrid"||!info;hybrid.innerHTML=info?`<h3>${api.escapeHtml(info.title)}</h3><p>${api.escapeHtml(info.summary)}</p>${sourceLink(info)}`:"";requestAnimationFrame(()=>map.invalidateSize())}
function renderInformation(category){setSide("information");const item=record.information.find(x=>x.category===category.id),host=$("#practical-info"),count=$("#practical-result-count");count.textContent="Kommunövergripande information";if(!item){host.innerHTML="<p>Verifierad information saknas för kategorin.</p>";return}const contacts=[];if(item.contact?.phone)contacts.push(`<a href="tel:${item.contact.phone.replace(/[^+\d]/g,"")}">${api.escapeHtml(item.contact.phone)}</a>`);if(item.contact?.email)contacts.push(`<a href="mailto:${api.escapeHtml(item.contact.email)}">${api.escapeHtml(item.contact.email)}</a>`);if(item.contact?.afterHours)contacts.push(`<span>${api.escapeHtml(item.contact.afterHours)}</span>`);host.innerHTML=`<span class="practical-info-label">PRAKTISK INFORMATION</span><h2>${api.escapeHtml(item.title)}</h2><p class="practical-summary">${api.escapeHtml(item.summary)}</p>${item.sections.map(s=>`<section><h3>${api.escapeHtml(s.heading)}</h3>${s.body?`<p>${api.escapeHtml(s.body)}</p>`:""}${s.items?`<ul>${s.items.map(x=>`<li>${api.escapeHtml(x)}</li>`).join("")}</ul>`:""}</section>`).join("")}${contacts.length?`<section class="practical-contact"><h3>Kontakt</h3>${contacts.join("")}</section>`:""}${sourceLink(item)}`}
function selectCategory(){const category=record.categories.find(c=>c.id===$("#practical-category").value);if(!category)return;$("#practical-category-description").textContent=category.description;$("#practical-flip").dataset.presentationType=category.presentationType;if(category.presentationType==="information")renderInformation(category);else renderMap(category)}
async function init(){const name=api.municipality();$("#practical-place").textContent=name;document.title=`Praktiskt i ${name} – återvinning, sophämtning & lokal service | DinPuls`;document.querySelector('meta[name="description"]').content=`Praktisk lokal vardagsinformation om återvinning, parkering, vatten och mer i ${name}.`;$("#practical-home-link").href=`index.html?kommun=${encodeURIComponent(name)}`;try{record=await api.record(name)}catch{$("#practical-empty").hidden=false;$("#practical-empty").textContent="Praktiskt-informationen kunde inte hämtas just nu.";return}if(!record){$("#practical-controls").hidden=true;$("#practical-flip").hidden=true;$("#practical-empty").hidden=false;$("#practical-empty").innerHTML=`<h2>Praktiskt är ännu inte anslutet för ${api.escapeHtml(name)}</h2><p>Vi visar aldrig information från en annan kommun som ersättning.</p>`;return}const settlement=$("#practical-settlement"),category=$("#practical-category");settlement.innerHTML=record.settlements.map(x=>`<option value="${api.escapeHtml(x.id)}">${api.escapeHtml(x.label)}</option>`).join("");category.innerHTML=record.categories.map(x=>`<option value="${api.escapeHtml(x.id)}">${api.escapeHtml(x.label)}</option>`).join("");settlement.addEventListener("change",()=>{const c=record.categories.find(x=>x.id===category.value);if(c.presentationType!=="information")renderMap(c)});category.addEventListener("change",selectCategory);selectCategory();window.lucide?.createIcons()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
