-- Forward-only. The Worker also creates this schema lazily via ensureDatabase.
CREATE TABLE IF NOT EXISTS self_service_orders (id TEXT PRIMARY KEY, company_user_id INTEGER NOT NULL, foundation_contract_id TEXT NOT NULL, billing_type TEXT NOT NULL, snapshot_json TEXT NOT NULL, snapshot_hash TEXT NOT NULL, status TEXT NOT NULL, expires_at TEXT NOT NULL, confirmed_at TEXT, created_at TEXT NOT NULL, FOREIGN KEY(company_user_id) REFERENCES business_users(id), FOREIGN KEY(foundation_contract_id) REFERENCES ad_contracts(id));
CREATE INDEX IF NOT EXISTS self_service_orders_company ON self_service_orders(company_user_id, created_at);
CREATE TABLE IF NOT EXISTS self_service_holds (order_id TEXT NOT NULL, company_user_id INTEGER NOT NULL, municipality TEXT NOT NULL, slot_id TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL, status TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(order_id, municipality, slot_id), FOREIGN KEY(order_id) REFERENCES self_service_orders(id));
CREATE INDEX IF NOT EXISTS self_service_holds_period ON self_service_holds(municipality, slot_id, start_date, end_date, status, expires_at);
CREATE TRIGGER IF NOT EXISTS prevent_self_service_hold_overlap BEFORE INSERT ON self_service_holds BEGIN SELECT CASE WHEN EXISTS (SELECT 1 FROM self_service_holds h WHERE h.municipality=NEW.municipality AND h.slot_id=NEW.slot_id AND h.start_date<=NEW.end_date AND h.end_date>=NEW.start_date AND (h.status='committed' OR (h.status='held' AND h.expires_at>NEW.created_at))) OR EXISTS (SELECT 1 FROM contract_slot_reservations r WHERE r.municipality=NEW.municipality AND r.slot_id=NEW.slot_id AND r.start_date<=NEW.end_date AND r.end_date>=NEW.start_date) THEN RAISE(ABORT, 'SLOT_PERIOD_OCCUPIED') END; END;
CREATE TRIGGER IF NOT EXISTS prevent_contract_self_service_overlap BEFORE INSERT ON contract_slot_reservations BEGIN SELECT CASE WHEN EXISTS (SELECT 1 FROM self_service_holds h WHERE h.municipality=NEW.municipality AND h.slot_id=NEW.slot_id AND h.start_date<=NEW.end_date AND h.end_date>=NEW.start_date AND (h.status='committed' OR (h.status='held' AND h.expires_at>NEW.created_at))) THEN RAISE(ABORT, 'SLOT_PERIOD_OCCUPIED') END; END;
CREATE TABLE IF NOT EXISTS self_service_purchases (id TEXT PRIMARY KEY, order_id TEXT NOT NULL, company_user_id INTEGER NOT NULL, foundation_contract_id TEXT NOT NULL, municipality TEXT NOT NULL, slot_id TEXT NOT NULL, placement_label TEXT NOT NULL, billing_type TEXT NOT NULL, unit_price INTEGER NOT NULL, vat_amount INTEGER NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL, contract_version TEXT NOT NULL, billing_status TEXT NOT NULL DEFAULT 'waiting_for_launch', publication_status TEXT NOT NULL DEFAULT 'waiting_for_launch', confirmation_json TEXT NOT NULL, confirmation_hash TEXT NOT NULL, confirmed_at TEXT NOT NULL, spiris_invoice_id TEXT, FOREIGN KEY(order_id) REFERENCES self_service_orders(id));
CREATE UNIQUE INDEX IF NOT EXISTS self_service_purchases_order_slot ON self_service_purchases(order_id, municipality, slot_id);
CREATE INDEX IF NOT EXISTS self_service_purchases_company ON self_service_purchases(company_user_id, confirmed_at);
CREATE TRIGGER IF NOT EXISTS prevent_invalid_self_service_purchase BEFORE INSERT ON self_service_purchases BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM self_service_orders o JOIN self_service_holds h ON h.order_id=o.id WHERE o.id=NEW.order_id AND o.company_user_id=NEW.company_user_id AND o.foundation_contract_id=NEW.foundation_contract_id AND o.status='confirmed' AND o.confirmed_at=NEW.confirmed_at AND h.company_user_id=NEW.company_user_id AND h.municipality=NEW.municipality AND h.slot_id=NEW.slot_id AND h.status='held' AND h.expires_at>NEW.confirmed_at) THEN RAISE(ABORT, 'ORDER_CONFLICT') END; END;
