const ADMIN_USER='snuttis8290';
const EXPECTED_PASSWORD='Flisan5917';
const CONTRACT_VERSION='3.0';
const municipalities=['Åmål','Bengtsfors','Dals-Ed','Färgelanda','Mellerud','Arvika','Eda','Filipstad','Forshaga','Grums','Hagfors','Hammarö','Karlstad','Kil','Kristinehamn','Munkfors','Storfors','Sunne','Säffle','Torsby','Årjäng'];
const AD_SLOTS=window.DINPULS_AD_INVENTORY||[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function contracts(){try{return JSON.parse(localStorage.getItem('dp-contracts')||'[]')}catch{return []}}
function writeContracts(x){localStorage.setItem('dp-contracts',JSON.stringify(x))}function save(c){const x=contracts();x.unshift(c);writeContracts(x)}
function updateContract(id,patch){const x=contracts(),i=x.findIndex(c=>c.id===id);if(i<0)return;x[i]={...x[i],...patch,updated:new Date().toISOString()};writeContracts(x);render()}
function showLogin(){$('#loginView').hidden=false;$('#appView').hidden=true}function login(){sessionStorage.setItem('dp-admin','1');$('#loginView').hidden=true;$('#appView').hidden=false;scrollTo(0,0);render()}
function money(n){return Number(n||0).toLocaleString('sv-SE')+' kr'}function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function contractNumber(){const y=new Date().getFullYear(),nums=contracts().map(c=>String(c.id||'')).filter(x=>x.startsWith(`DP-${y}-`)).map(x=>+x.split('-').pop()||0);return `DP-${y}-${String(Math.max(0,...nums)+1).padStart(4,'0')}`}
function endDateFrom(start){if(!start)return '';const d=new Date(start+'T12:00:00');d.setFullYear(d.getFullYear()+1);d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)}
function activeCompanies(cs){const map=new Map();cs.filter(c=>c.status==='Aktivt').forEach(c=>{const key=(c.orgNo||c.company||'').toLowerCase();if(!map.has(key))map.set(key,c)});return [...map.values()].sort((a,b)=>String(a.company).localeCompare(String(b.company),'sv'))}
function slotById(id){return AD_SLOTS.find(s=>s.id===id)}function occupiedMap(cs=contracts()){const map=new Map();cs.filter(c=>c.status==='Aktivt').forEach(c=>(c.placements||[]).forEach(p=>{const id=p.slotId||p.slot;if(slotById(id))map.set(`${c.municipality}|${id}`,c)}));return map}
function availableSlots(municipality,excludeRows=[]){const occupied=occupiedMap(),selected=new Set(excludeRows.map(r=>r.querySelector('.slot')?.value).filter(Boolean));return AD_SLOTS.filter(s=>!occupied.has(`${municipality}|${s.id}`)&&!selected.has(s.id))}
function statusActions(c){if(c.status==='Utkast')return `<button class="secondary contract-action" data-id="${c.id}" data-status="Skickat">Markera skickat</button>`;if(c.status==='Skickat')return `<button class="primary contract-action" data-id="${c.id}" data-status="Aktivt">Markera signerat</button>`;if(c.status==='Aktivt')return `<button class="secondary contract-action" data-id="${c.id}" data-status="Avslutat">Avsluta</button>`;return ''}
function render(){const cs=contracts(),active=cs.filter(c=>c.status==='Aktivt'),drafts=cs.filter(c=>c.status==='Utkast'),mrr=active.reduce((s,c)=>s+Number(c.price||0)*(c.placements?.length||0),0);$('#activeContracts').textContent=active.length;$('#mrr').textContent=money(mrr);$('#arr').textContent=money(mrr*12);$('#drafts').textContent=drafts.length;$('#contractList').innerHTML=cs.length?`<div class="contract-row"><strong>Avtal</strong><strong>Företag</strong><strong>Kommun / plats</strong><strong>Status</strong></div>`+cs.map(c=>`<div class="contract-row contract-click" data-contract="${c.id}"><span><b>${escapeHtml(c.id)}</b><small>v${escapeHtml(c.contractVersion||'äldre')}</small></span><span><b>${escapeHtml(c.company)}</b><small>${escapeHtml(c.contact||'')}</small></span><span>${escapeHtml(c.municipality)} · ${(c.placements||[]).map(p=>escapeHtml(p.slotId||p.slot)).join(', ')}<small>${escapeHtml(c.startDate||'')} ${c.endDate?'– '+escapeHtml(c.endDate):''}</small></span><span><span class="badge ${c.status==='Utkast'?'draft':''}">${escapeHtml(c.status)}</span></span></div>`).join(''):'<div class="empty-state">Inga avtal ännu.</div>';$('#recentContracts').innerHTML=cs.length?cs.slice(0,5).map(c=>`<div class="recent-row"><span><b>${escapeHtml(c.company)}</b><small>${escapeHtml(c.municipality)}</small></span><span class="badge">${escapeHtml(c.status)}</span><small>${new Date(c.created).toLocaleDateString('sv-SE')}</small></div>`).join(''):'<div class="empty-state">När du skapar avtal visas de senaste här.</div>';renderCompanies(cs);renderInventory();bindContractRows()}
function bindContractRows(){$$('[data-contract]').forEach(r=>r.onclick=()=>openContract(r.dataset.contract));$$('.contract-action').forEach(b=>b.onclick=e=>{e.stopPropagation();updateContract(b.dataset.id,{status:b.dataset.status,activated:b.dataset.status==='Aktivt'?new Date().toISOString():undefined})})}
function openContract(id){const c=contracts().find(x=>x.id===id);if(!c)return;let d=$('#contractDialog');if(!d){d=document.createElement('dialog');d.id='contractDialog';d.className='company-dialog';document.body.append(d)}d.innerHTML=`<button class="dialog-x" onclick="this.closest('dialog').close()">×</button><span class="eyebrow">ANNONSAVTAL v${escapeHtml(c.contractVersion||'3.0')}</span><h2>${escapeHtml(c.company)}</h2><p class="muted">${escapeHtml(c.id)} · ${escapeHtml(c.status)}</p><div class="contact-details"><div><small>Kommun</small><strong>${escapeHtml(c.municipality)}</strong></div><div><small>Period</small><strong>${escapeHtml(c.startDate)} – ${escapeHtml(c.endDate)}</strong></div><div><small>Månadspris</small><strong>${money(c.monthlyTotal)}</strong></div><div><small>Årsvärde</small><strong>${money(c.annualTotal)}</strong></div><div><small>Kontakt</small><strong>${escapeHtml(c.contact)}<br>${escapeHtml(c.phone)}</strong></div><div><small>E-post</small><strong>${escapeHtml(c.email)}</strong></div></div><h3>Annonsplatser</h3><p>${(c.placements||[]).map(p=>`<b>${escapeHtml(p.slotId)}</b> – ${escapeHtml(p.location)}`).join('<br>')}</p><p><b>4 annonsbyten</b> ingår under avtalsperioden.</p><div class="actions">${statusActions(c)}</div>`;d.showModal();d.querySelectorAll('.contract-action').forEach(b=>b.onclick=()=>{updateContract(b.dataset.id,{status:b.dataset.status,activated:b.dataset.status==='Aktivt'?new Date().toISOString():undefined});d.close()})}
function renderCompanies(cs){const companies=activeCompanies(cs),list=$('#companyList');list.innerHTML=companies.length?companies.map((c,i)=>`<button type="button" class="company-row" data-company-index="${i}"><span><b>${escapeHtml(c.company)}</b><small>${escapeHtml(c.orgNo||'')}</small></span><span>${escapeHtml(c.municipality||'')}</span><span>${escapeHtml(c.contact||'')}</span><span class="company-arrow">→</span></button>`).join(''):'<div class="company-empty"><span>◉</span><h3>Inga aktiva företag ännu</h3><p>När ett avtal får status <b>Aktivt</b> visas företaget automatiskt här.</p></div>';$$('[data-company-index]').forEach(btn=>btn.onclick=()=>openCompany(companies[+btn.dataset.companyIndex]))}
function openCompany(c){$('#companyDialogName').textContent=c.company||'';$('#companyDialogOrg').textContent=c.orgNo?'Organisationsnummer '+c.orgNo:'';$('#companyDialogContact').textContent=c.contact||'–';const p=$('#companyDialogPhone');p.textContent=c.phone||'–';p.removeAttribute('href');if(c.phone)p.href='tel:'+c.phone.replace(/\s/g,'');const e=$('#companyDialogEmail');e.textContent=c.email||'–';e.removeAttribute('href');if(c.email)e.href='mailto:'+c.email;$('#companyDialogMunicipality').textContent=c.municipality||'–';$('#companyDialog').showModal()}
function renderInventory(){const municipality=$('#inventoryMunicipality').value||municipalities[0],occ=occupiedMap();let occupied=0;$('#inventoryList').innerHTML=AD_SLOTS.map(s=>{const c=occ.get(`${municipality}|${s.id}`);if(c)occupied++;return `<div class="inventory-row"><b>${s.id}</b><span>${escapeHtml(s.label)}</span><small>${escapeHtml(s.location)}</small><span class="badge ${c?'occupied':'free'}">${c?'Upptagen':'Ledig'}</span><span>${c?escapeHtml(c.company):'–'}</span></div>`}).join('');$('#inventoryTotal').textContent=AD_SLOTS.length;$('#inventoryFree').textContent=AD_SLOTS.length-occupied;$('#inventoryOccupied').textContent=occupied}
function refreshPlacementOptions(){const municipality=$('#municipality').value;$$('.placement').forEach(row=>{const select=row.querySelector('.slot'),current=select.value,others=$$('.placement').filter(r=>r!==row),choices=availableSlots(municipality,others);select.innerHTML=choices.map(s=>`<option value="${s.id}">${s.id} · ${escapeHtml(s.label)}</option>`).join('');if(choices.some(s=>s.id===current))select.value=current})}
function addPlacement(){const choices=availableSlots($('#municipality').value,$$('.placement'));if(!choices.length)return alert('Det finns inga fler lediga annonsplatser i vald kommun.');const row=document.createElement('div');row.className='placement';row.innerHTML=`<label>Annonsplats<select class="slot">${choices.map(s=>`<option value="${s.id}">${s.id} · ${escapeHtml(s.label)}</option>`).join('')}</select></label><label>Placering<input class="slot-location" value="${escapeHtml(choices[0].location)}" disabled></label><button type="button" class="secondary">Ta bort</button>`;const sel=row.querySelector('.slot'),loc=row.querySelector('.slot-location');sel.onchange=()=>{loc.value=slotById(sel.value)?.location||'';refreshPlacementOptions()};row.querySelector('button').onclick=()=>{row.remove();refreshPlacementOptions()};$('#placements').append(row);refreshPlacementOptions()}
function openView(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$$('.view').forEach(v=>v.hidden=v.id!==id);if(id==='inventory')renderInventory();scrollTo(0,0)}function openNewContract(){openView('contracts');$('#contractForm').hidden=false;$('#contractForm').reset();$('#placements').innerHTML='';const today=new Date().toISOString().slice(0,10);$('#startDate').value=today;$('#endDate').value=endDateFrom(today);addPlacement()}
function init(){municipalities.sort((a,b)=>a.localeCompare(b,'sv')).forEach(m=>{$('#municipality').add(new Option(m,m));$('#inventoryMunicipality').add(new Option(m,m))});$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#username').value.trim()===ADMIN_USER&&$('#password').value===EXPECTED_PASSWORD){$('#loginError').hidden=true;login()}else $('#loginError').hidden=false};$('#logout').onclick=()=>{sessionStorage.removeItem('dp-admin');showLogin()};$$('.tab').forEach(b=>b.onclick=()=>openView(b.dataset.view));$$('[data-open]').forEach(b=>b.onclick=()=>b.dataset.new?openNewContract():openView(b.dataset.open));$('#closeCompanyDialog').onclick=()=>$('#companyDialog').close();$('#inventoryMunicipality').onchange=renderInventory;$('#municipality').onchange=()=>{$('#placements').innerHTML='';addPlacement()};$('#startDate').onchange=()=>$('#endDate').value=endDateFrom($('#startDate').value);$('#addPlacement').onclick=addPlacement;$('#newContract').onclick=openNewContract;$('#cancelContract').onclick=()=>$('#contractForm').hidden=true;$('#contractForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),municipality=f.get('municipality'),ids=$$('.placement').map(r=>r.querySelector('.slot').value),occupied=occupiedMap();if(!ids.length)return alert('Lägg till minst en annonsplats.');if(new Set(ids).size!==ids.length)return alert('Samma annonsplats kan inte bokas två gånger.');for(const id of ids){if(!slotById(id))return alert(`Annonsplats ${id} finns inte.`);if(occupied.has(`${municipality}|${id}`))return alert(`Annonsplats ${id} är redan upptagen.`)}const placements=ids.map(id=>{const s=slotById(id);return {slotId:id,module:s.module,group:s.group,label:s.label,location:s.location}}),price=+f.get('price'),annualPrice=+f.get('annualPrice'),startDate=f.get('startDate');save({id:contractNumber(),contractVersion:CONTRACT_VERSION,company:f.get('company'),orgNo:f.get('orgNo'),contact:f.get('contact'),email:f.get('email'),phone:f.get('phone'),municipality,placements,price,annualPrice,monthlyTotal:price*placements.length,annualTotal:annualPrice*placements.length,startDate,endDate:endDateFrom(startDate),months:12,includedChanges:4,status:'Utkast',created:new Date().toISOString()});e.target.reset();$('#placements').innerHTML='';$('#contractForm').hidden=true;render()};if(sessionStorage.getItem('dp-admin')==='1')login();else showLogin()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();