const ADMIN_USER='snuttis8290';
const EXPECTED_PASSWORD='Flisan5917';
const municipalities=['Åmål','Bengtsfors','Dals-Ed','Färgelanda','Mellerud','Arvika','Eda','Filipstad','Forshaga','Grums','Hagfors','Hammarö','Karlstad','Kil','Kristinehamn','Munkfors','Storfors','Sunne','Säffle','Torsby','Årjäng'];
const AD_SLOTS=window.DINPULS_AD_INVENTORY||[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function contracts(){try{return JSON.parse(localStorage.getItem('dp-contracts')||'[]')}catch{return []}}
function save(c){const x=contracts();x.unshift(c);localStorage.setItem('dp-contracts',JSON.stringify(x))}
function showLogin(){$('#loginView').hidden=false;$('#appView').hidden=true}function login(){sessionStorage.setItem('dp-admin','1');$('#loginView').hidden=true;$('#appView').hidden=false;scrollTo(0,0);render()}
function money(n){return Number(n||0).toLocaleString('sv-SE')+' kr'}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function activeCompanies(cs){const map=new Map();cs.filter(c=>c.status==='Aktivt').forEach(c=>{const key=(c.orgNo||c.company||'').toLowerCase();if(!map.has(key))map.set(key,c)});return [...map.values()].sort((a,b)=>String(a.company).localeCompare(String(b.company),'sv'))}
function slotById(id){return AD_SLOTS.find(s=>s.id===id)}
function occupiedMap(cs=contracts()){const map=new Map();cs.filter(c=>c.status==='Aktivt').forEach(c=>(c.placements||[]).forEach(p=>{const id=p.slotId||p.slot;if(slotById(id))map.set(`${c.municipality}|${id}`,c)}));return map}
function availableSlots(municipality,excludeRows=[]){const occupied=occupiedMap(),selected=new Set(excludeRows.map(r=>r.querySelector('.slot')?.value).filter(Boolean));return AD_SLOTS.filter(s=>!occupied.has(`${municipality}|${s.id}`)&&!selected.has(s.id))}
function render(){const cs=contracts(),active=cs.filter(c=>c.status==='Aktivt'),drafts=cs.filter(c=>c.status==='Utkast'),mrr=active.reduce((s,c)=>s+Number(c.price||0)*(c.placements?.length||0),0);$('#activeContracts').textContent=active.length;$('#mrr').textContent=money(mrr);$('#arr').textContent=money(mrr*12);$('#drafts').textContent=drafts.length;$('#contractList').innerHTML=cs.length?`<div class="contract-row"><strong>Avtal</strong><strong>Företag</strong><strong>Kommun / plats</strong><strong>Status</strong></div>`+cs.map(c=>`<div class="contract-row"><span>${c.id}</span><span><b>${escapeHtml(c.company)}</b><small>${escapeHtml(c.contact||'')}</small></span><span>${escapeHtml(c.municipality)} · ${(c.placements||[]).map(p=>escapeHtml(p.slotId||p.slot)).join(', ')}</span><span><span class="badge ${c.status==='Utkast'?'draft':''}">${c.status}</span></span></div>`).join(''):'<div class="empty-state">Inga avtal ännu.</div>';$('#recentContracts').innerHTML=cs.length?cs.slice(0,5).map(c=>`<div class="recent-row"><span><b>${escapeHtml(c.company)}</b><small>${escapeHtml(c.municipality)}</small></span><span class="badge ${c.status==='Utkast'?'draft':''}">${c.status}</span><small>${new Date(c.created).toLocaleDateString('sv-SE')}</small></div>`).join(''):'<div class="empty-state">När du skapar avtal visas de senaste här.</div>';renderCompanies(cs);renderInventory()}
function renderCompanies(cs){const companies=activeCompanies(cs),list=$('#companyList');list.innerHTML=companies.length?companies.map((c,i)=>`<button type="button" class="company-row" data-company-index="${i}"><span><b>${escapeHtml(c.company)}</b><small>${escapeHtml(c.orgNo||'')}</small></span><span>${escapeHtml(c.municipality||'')}</span><span>${escapeHtml(c.contact||'')}</span><span class="company-arrow">→</span></button>`).join(''):'<div class="company-empty"><span>◉</span><h3>Inga aktiva företag ännu</h3><p>När ett avtal får status <b>Aktivt</b> visas företaget automatiskt här.</p></div>';$$('[data-company-index]').forEach(btn=>btn.onclick=()=>openCompany(companies[+btn.dataset.companyIndex]))}
function openCompany(c){$('#companyDialogName').textContent=c.company||'';$('#companyDialogOrg').textContent=c.orgNo?'Organisationsnummer '+c.orgNo:'';$('#companyDialogContact').textContent=c.contact||'–';const p=$('#companyDialogPhone');p.textContent=c.phone||'–';p.removeAttribute('href');if(c.phone)p.href='tel:'+c.phone.replace(/\s/g,'');const e=$('#companyDialogEmail');e.textContent=c.email||'–';e.removeAttribute('href');if(c.email)e.href='mailto:'+c.email;$('#companyDialogMunicipality').textContent=c.municipality||'–';$('#companyDialog').showModal()}
function renderInventory(){const municipality=$('#inventoryMunicipality').value||municipalities[0],occ=occupiedMap();let occupied=0;$('#inventoryList').innerHTML=AD_SLOTS.map(s=>{const c=occ.get(`${municipality}|${s.id}`);if(c)occupied++;return `<div class="inventory-row"><b>${s.id}</b><span>${escapeHtml(s.label)}</span><small>${escapeHtml(s.location)}</small><span class="badge ${c?'occupied':'free'}">${c?'Upptagen':'Ledig'}</span><span>${c?escapeHtml(c.company):'–'}</span></div>`}).join('');$('#inventoryTotal').textContent=AD_SLOTS.length;$('#inventoryFree').textContent=AD_SLOTS.length-occupied;$('#inventoryOccupied').textContent=occupied}
function refreshPlacementOptions(){const municipality=$('#municipality').value;$$('.placement').forEach(row=>{const select=row.querySelector('.slot'),current=select.value,others=$$('.placement').filter(r=>r!==row);const choices=availableSlots(municipality,others);select.innerHTML=choices.map(s=>`<option value="${s.id}">${s.id} · ${escapeHtml(s.label)}</option>`).join('');if(choices.some(s=>s.id===current))select.value=current})}
function addPlacement(){const municipality=$('#municipality').value,choices=availableSlots(municipality,$$('.placement'));if(!choices.length)return alert('Det finns inga fler lediga annonsplatser i vald kommun.');const row=document.createElement('div');row.className='placement';row.innerHTML=`<label>Annonsplats<select class="slot">${choices.map(s=>`<option value="${s.id}">${s.id} · ${escapeHtml(s.label)}</option>`).join('')}</select></label><label>Placering<input class="slot-location" value="${escapeHtml(choices[0].location)}" disabled></label><button type="button" class="secondary">Ta bort</button>`;const sel=row.querySelector('.slot'),loc=row.querySelector('.slot-location');sel.onchange=()=>{loc.value=slotById(sel.value)?.location||'';refreshPlacementOptions()};row.querySelector('button').onclick=()=>{row.remove();refreshPlacementOptions()};$('#placements').append(row);refreshPlacementOptions()}
function openView(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$$('.view').forEach(v=>v.hidden=v.id!==id);if(id==='inventory')renderInventory();scrollTo(0,0)}
function openNewContract(){openView('contracts');$('#contractForm').hidden=false;$('#placements').innerHTML='';addPlacement();setTimeout(()=>$('#contractForm').scrollIntoView({behavior:'smooth'}),50)}
function init(){municipalities.sort((a,b)=>a.localeCompare(b,'sv')).forEach(m=>{$('#municipality').add(new Option(m,m));$('#inventoryMunicipality').add(new Option(m,m))});$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#username').value.trim()===ADMIN_USER&&$('#password').value===EXPECTED_PASSWORD){$('#loginError').hidden=true;login()}else $('#loginError').hidden=false};$('#logout').onclick=()=>{sessionStorage.removeItem('dp-admin');showLogin()};$$('.tab').forEach(b=>b.onclick=()=>openView(b.dataset.view));$$('[data-open]').forEach(b=>b.onclick=()=>b.dataset.new?openNewContract():openView(b.dataset.open));$('#closeCompanyDialog').onclick=()=>$('#companyDialog').close();$('#companyDialog').onclick=e=>{if(e.target===$('#companyDialog'))$('#companyDialog').close()};$('#inventoryMunicipality').onchange=renderInventory;$('#municipality').onchange=()=>{$('#placements').innerHTML='';addPlacement()};$('#addPlacement').onclick=addPlacement;$('#newContract').onclick=openNewContract;$('#cancelContract').onclick=()=>$('#contractForm').hidden=true;$('#contractForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),municipality=f.get('municipality'),ids=$$('.placement').map(r=>r.querySelector('.slot').value);if(!ids.length)return alert('Lägg till minst en annonsplats.');if(new Set(ids).size!==ids.length)return alert('Samma annonsplats kan inte bokas två gånger.');const occupied=occupiedMap();for(const id of ids){if(!slotById(id))return alert(`Annonsplats ${id} finns inte i DinPuls platsregister.`);if(occupied.has(`${municipality}|${id}`))return alert(`Annonsplats ${id} är redan upptagen i ${municipality}.`)}const placements=ids.map(id=>{const s=slotById(id);return {slotId:id,module:s.module,group:s.group,label:s.label,location:s.location}});save({id:'DP-'+String(Date.now()).slice(-6),company:f.get('company'),orgNo:f.get('orgNo'),contact:f.get('contact'),email:f.get('email'),phone:f.get('phone'),municipality,placements,price:+f.get('price'),months:12,status:'Utkast',created:new Date().toISOString()});e.target.reset();$('#placements').innerHTML='';$('#contractForm').hidden=true;render()};if(sessionStorage.getItem('dp-admin')==='1')login();else showLogin()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();