import { CONTRACT_TERMS, CONTRACT_VERSION, calculateContractPrice } from "../cloudflare/contract-v4.js";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=v=>`${Number(v||0).toLocaleString("sv-SE")} kr`; const pads=new Map();
const termsHtml=()=>CONTRACT_TERMS.map(t=>`<article class="wizard-term"><h4>${esc(t.title)}</h4>${t.paragraphs.map(p=>`<p>${esc(p)}</p>`).join("")}</article>`).join("");

function pad(canvas){const ctx=canvas.getContext("2d");let down=false,drawn=false;const resize=()=>{const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=180*d;ctx.setTransform(d,0,0,d,0,0);ctx.lineWidth=2.2;ctx.lineCap="round";ctx.strokeStyle="#17364d"};const point=e=>{const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:p.clientX-r.left,y:p.clientY-r.top}};canvas.onpointerdown=e=>{e.preventDefault();down=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};canvas.onpointermove=e=>{if(!down)return;e.preventDefault();const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();drawn=true};canvas.onpointerup=canvas.onpointerleave=()=>down=false;const clear=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);drawn=false};canvas.closest(".signature-box").querySelector("button").onclick=clear;resize();pads.set(canvas.id,{canvas,clear,isDrawn:()=>drawn})}
function show(n){$$('[data-wizard-step]').forEach(s=>s.hidden=Number(s.dataset.wizardStep)!==n);$$('[data-step-marker]').forEach(m=>{const x=Number(m.dataset.stepMarker);m.classList.toggle("active",x===n);m.classList.toggle("done",x<n)});$("#contractForm")?.scrollIntoView({behavior:"smooth",block:"start"})}
function validDetails(form){for(const f of form.querySelectorAll('[data-wizard-step="2"] input[required],[data-wizard-step="2"] select[required]'))if(!f.checkValidity()){f.reportValidity();f.focus();return false}const ids=$$(".placement").map(r=>r.querySelector(".slot")?.value).filter(Boolean);if(!ids.length||new Set(ids).size!==ids.length){alert("Välj minst en unik annonsplats.");return false}return true}
function preview(form){const d=new FormData(form),ps=$$(".placement").map(r=>({slotId:r.querySelector(".slot")?.value||"",location:r.querySelector(".slot-location")?.value||""})),price=calculateContractPrice(d.get("billingType"),ps.length);$("#wizardCalculatedPrice").textContent=`${price.label}: ${money(price.invoiceTotal)} ${price.interval}, exkl. moms`;$("#contractPreview").innerHTML=`<header><div><span class="eyebrow">DINPULS ANNONSAVTAL v${CONTRACT_VERSION}</span><h3>${esc(d.get("company"))}</h3><p>${esc(d.get("orgNo"))}</p></div><strong>Samma innehåll låses vid signering</strong></header><div class="preview-grid"><div><small>Kontakt</small><b>${esc(d.get("contact"))}</b><span>${esc(d.get("email"))}<br>${esc(d.get("phone"))}</span></div><div><small>Kommun</small><b>${esc(d.get("municipality"))}</b></div><div><small>Period</small><b>${esc(d.get("startDate"))} – ${esc(d.get("endDate"))}</b></div><div><small>Betalningsform</small><b>${esc(price.label)}</b></div><div><small>Pris per plats</small><b>${money(price.unitPrice)} / ${esc(price.interval)}</b></div><div><small>Total</small><b>${money(price.invoiceTotal)} · exkl. moms · ${esc(price.paymentTerms)}</b></div></div><h4>Annonsplatser</h4><ul>${ps.map(p=>`<li><b>${esc(p.slotId)}</b><span>${esc(p.location)}</span></li>`).join("")}</ul>${d.get("valueNote")?`<h4>Särskilda villkor</h4><p>${esc(d.get("valueNote"))}</p>`:""}<div class="preview-terms"><h4>Fullständiga v4.0-villkor</h4>${termsHtml()}</div>`}
function signatures(){const c=pads.get("customerSignature"),p=pads.get("dinpulsSignature"),r={customerSignerName:$("#customerSignerName")?.value.trim(),customerSignerTitle:$("#customerSignerTitle")?.value.trim(),dinpulsSignerName:$("#dinpulsSignerName")?.value.trim(),dinpulsSignerTitle:$("#dinpulsSignerTitle")?.value.trim(),customerSignature:c?.canvas.toDataURL("image/png"),dinpulsSignature:p?.canvas.toDataURL("image/png")};r.valid=Boolean(r.customerSignerName&&r.customerSignerTitle&&r.dinpulsSignerName&&r.dinpulsSignerTitle&&c?.isDrawn()&&p?.isDrawn());return r}
function init(){const f=$("#contractForm");if(!f)return;const h=f.querySelector(".panel-heading"),g=f.querySelector(".grid2"),ph=[...f.children].find(n=>n.tagName==="H3"),pl=$("#placements"),add=$("#addPlacement"),tot=f.querySelector(".totals"),actions=f.querySelector(".actions"),foot=f.querySelector(".muted.small");const nav=document.createElement("ol");nav.className="contract-stepper";nav.innerHTML=["Avtalet","Uppgifter","Förhandsgranska","Signering"].map((x,i)=>`<li data-step-marker="${i+1}"><span>${i+1}</span><b>${x}</b></li>`).join("");h.after(nav);
const s1=document.createElement("section");s1.className="wizard-step";s1.dataset.wizardStep=1;s1.innerHTML=`<div class="wizard-intro"><span class="eyebrow">STEG 1 AV 4</span><h3>Gå igenom hela avtalet</h3><p>Villkoren nedan är samma centrala innehåll som låses och förs in i PDF-kopian.</p></div><div class="wizard-contract"><header><strong>DinPuls.se</strong><span>ANNONSAVTAL · v${CONTRACT_VERSION}</span></header>${termsHtml()}</div><label class="wizard-confirm"><input id="termsReviewed" type="checkbox"> <span>Jag och kunden har gått igenom samtliga villkor ovan.</span></label><div class="wizard-nav"><button type="button" class="primary" data-wizard-next="2" disabled>Fortsätt →</button></div>`;
const s2=document.createElement("section");s2.className="wizard-step";s2.dataset.wizardStep=2;s2.innerHTML=`<div class="wizard-intro"><span class="eyebrow">STEG 2 AV 4</span><h3>Avtalsuppgifter</h3><p>Pris räknas automatiskt från betalningsform och antal platser.</p></div>`;[g,ph,pl,add,tot].forEach(n=>s2.append(n));s2.insertAdjacentHTML("beforeend",`<div class="wizard-nav"><button type="button" class="secondary" data-wizard-prev="1">← Till villkoren</button><button type="button" class="primary" data-wizard-next="3">Förhandsgranska →</button></div>`);
const s3=document.createElement("section");s3.className="wizard-step";s3.dataset.wizardStep=3;s3.innerHTML=`<div class="wizard-intro"><span class="eyebrow">STEG 3 AV 4</span><h3>Kontrollera exakt vad som signeras</h3><p>Efter signering kan innehållet inte ändras.</p></div><div id="contractPreview" class="wizard-preview"></div><div class="wizard-nav"><button type="button" class="secondary" data-wizard-prev="2">← Ändra</button><button type="button" class="primary" data-wizard-next="4">Till signering →</button></div>`;
const s4=document.createElement("section");s4.className="wizard-step";s4.dataset.wizardStep=4;s4.innerHTML=`<div class="wizard-intro"><span class="eyebrow">STEG 4 AV 4</span><h3>Underteckna avtalet</h3><p>Båda underskrifterna krävs innan PDF skapas och avtalet aktiveras.</p></div><div class="signature-grid"><section><h4>Företaget</h4><label>Namn<input id="customerSignerName" required></label><label>Befattning/roll<input id="customerSignerTitle" required></label><p class="signature-declaration">Genom att skriva under bekräftar jag att jag har rätt att företräda företaget och att jag godkänner avtalet och dess villkor.</p><div class="signature-box"><canvas id="customerSignature"></canvas><button type="button" class="secondary">Rensa</button></div></section><section><h4>DinPuls</h4><label>Namn<input id="dinpulsSignerName" required></label><label>Befattning/roll<input id="dinpulsSignerTitle" required></label><p class="signature-declaration">Jag undertecknar samma låsta avtalsversion för DinPuls.</p><div class="signature-box"><canvas id="dinpulsSignature"></canvas><button type="button" class="secondary">Rensa</button></div></section></div><div class="wizard-nav"><button type="button" class="secondary" data-wizard-prev="3">← Förhandsgranska</button></div>`;s4.querySelector(".wizard-nav").append(actions);if(foot)s4.append(foot);f.append(s1,s2,s3,s4);pad($("#customerSignature"));pad($("#dinpulsSignature"));$("#termsReviewed").onchange=e=>f.querySelector('[data-wizard-next="2"]').disabled=!e.target.checked;f.onclick=e=>{const n=e.target.closest("[data-wizard-next]"),p=e.target.closest("[data-wizard-prev]");if(n){const x=Number(n.dataset.wizardNext);if(x===3&&!validDetails(f))return;if(x>=3)preview(f);show(x)}if(p)show(Number(p.dataset.wizardPrev))};new MutationObserver(()=>{if(!f.hidden){$("#termsReviewed").checked=false;f.querySelector('[data-wizard-next="2"]').disabled=true;pads.forEach(x=>x.clear());show(1)}}).observe(f,{attributes:true,attributeFilter:["hidden"]});window.DinPulsContractWizard={signatures,terms:CONTRACT_TERMS,version:CONTRACT_VERSION};show(1)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
