(function(){"use strict";
const escape=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function render(data,now=Date.now()){
  const runLink=/^https:\/\/github\.com\/SirElin8290\/DinPuls\/actions\/runs\/\d+$/.test(data.runUrl||"")?`<a href="${escape(data.runUrl)}" target="_blank" rel="noopener">Visa nattkörningen i GitHub ↗</a>`:"";
  const age=now-Date.parse(data.generatedAt),late=data.completed!==true||!Number.isFinite(age)||age>32*3600000;
  const summary=data.summary||{},updates=Object.entries(data.updates||{}).filter(([,status])=>status!=="success");
  const labels={broken:"🔴 Bekräftat trasig",unverified:"🟡 Kunde inte verifieras",changed:"🟡 Innehåll ändrat – granska"};
  const sources=(data.sources||[]).filter(x=>x.state!=="reachable");
  const rows=sources.slice(0,100).map(x=>{const contexts=(x.contexts||[]).map(c=>[c.municipality,c.entity].filter(Boolean).join(" – ")); const url=/^https?:\/\//.test(x.url||"")?x.url:"";return `<article class="incident-card"><b>${escape(labels[x.state]||x.state)}</b><p>${escape([...new Set(contexts)].join("; "))}</p>${url?`<a href="${escape(url)}" target="_blank" rel="noopener noreferrer">Öppna källan ↗</a>`:""}<p>Senast nåbar: ${escape(x.lastSuccessfulAt?new Date(x.lastSuccessfulAt).toLocaleString("sv-SE"):"ännu inte verifierad")}</p></article>`;}).join("");
  const content=(data.contentIssues||[]).map(x=>`<li>${escape([x.municipality,x.entity].filter(Boolean).join(" – "))}: ${escape(x.message)}</li>`).join("");
  return `<h2>Nattlig källkontroll</h2><p>Planerad varje natt 01.00 svensk tid. Senaste slutförda kontroll: <b>${escape(new Date(data.generatedAt).toLocaleString("sv-SE"))}</b>.</p>${late?'<p class="health-load-error"><b>🔴 Nattkontrollen har uteblivit eller blivit för gammal.</b></p>':""}${updates.length?`<p class="health-load-error">🔴 Misslyckade uppdateringar: ${escape(updates.map(([name])=>name).join(", "))}</p>`:""}<p>${Number(summary.reachable||0)} nåbara källor · ${Number(summary.changed||0)} ändrade · ${Number(summary.unverified||0)} ej verifierade · ${Number(summary.broken||0)} bekräftat trasiga.</p><p>Nåbar betyder inte att alla uppgifter är verifierade. Systemet gissar aldrig en ny meny eller föreningsuppgift.</p><div class="incident-grid">${rows||'<p>Inga källproblem upptäckta i senaste kontrollen.</p>'}</div>${sources.length>100?'<p>De första 100 ärendena visas. Samtliga finns i hela rapporten.</p>':""}${content?`<h3>Innehåll som behöver granskas</h3><ul>${content}</ul>`:""}<p><a href="../docs/SOURCE-MONITOR-LATEST.md" target="_blank" rel="noopener">Öppna hela nattkontrollens rapport ↗</a> ${runLink}</p>`;
}
async function load(target){if(!target)return;try{const response=await fetch(`../data/source-monitor.json?time=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error("Kontrollrapport saknas");target.innerHTML=render(await response.json());}catch{target.innerHTML='<h2>Nattlig källkontroll</h2><p class="health-load-error">🟡 Ingen läsbar nattkontroll finns ännu. Kontrollera körningen i GitHub Actions.</p>';}}
window.DinPulsSourceMonitoring={render,load};
})();
