#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "script.js"
COMPONENT = ROOT / "components" / "missing-people.html"

old = '''    const items = Array.isArray(missingPeopleData?.municipalities?.[config.name]?.items)\n      ? missingPeopleData.municipalities[config.name].items.slice(0, 4)\n      : [];\n    status.textContent = `Kontrollerad ${generatedAt.toLocaleTimeString("sv-SE", { timeZone: STOCKHOLM_TIME_ZONE, hour: "2-digit", minute: "2-digit" })}`;\n    list.innerHTML = items.length\n      ? items.map(renderMissingPerson).join("")\n      : `<div class="missing-people-empty"><i data-lucide="circle-check"></i><span><strong>Inga publicerade efterlysningar i området</strong><small>Den officiella listan är kontrollerad för ${escapeHtml(config.name)} och angränsande DinPuls-kommuner.</small></span></div>`;\n'''
new = '''    const items = Array.isArray(missingPeopleData?.municipalities?.[config.name]?.items)\n      ? missingPeopleData.municipalities[config.name].items\n      : [];\n    const oneYearAgo = new Date();\n    oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);\n    const currentItems = items.filter(item => {\n      const published = new Date(item.publishedAt || "");\n      return Number.isNaN(published.getTime()) || published >= oneYearAgo;\n    }).slice(0, 4);\n    const olderItems = items.filter(item => {\n      const published = new Date(item.publishedAt || "");\n      return !Number.isNaN(published.getTime()) && published < oneYearAgo;\n    });\n    status.textContent = `Kontrollerad ${generatedAt.toLocaleTimeString("sv-SE", { timeZone: STOCKHOLM_TIME_ZONE, hour: "2-digit", minute: "2-digit" })}`;\n    list.innerHTML = items.length\n      ? `${currentItems.map(renderMissingPerson).join("")}${olderItems.length ? renderOlderMissingPeople(olderItems) : ""}`\n      : `<div class="missing-people-empty"><i data-lucide="circle-check"></i><span><strong>Inga publicerade efterlysningar i området</strong><small>Den officiella listan är kontrollerad för ${escapeHtml(config.name)} och angränsande DinPuls-kommuner.</small></span></div>`;\n'''

anchor = '''function renderMissingPerson(item) {\n'''
addition = '''function renderOlderMissingPeople(items) {\n  const visible = items.slice(0, 6);\n  return `<section class="missing-people-older" aria-label="Äldre aktiva efterlysningar">\n    <div class="missing-people-older-head"><span><i data-lucide="history"></i><strong>Äldre aktiva efterlysningar</strong></span><small>${items.length} ${items.length === 1 ? "fall" : "fall"} äldre än ett år</small></div>\n    <div class="missing-people-older-list">${visible.map(renderOlderMissingPerson).join("")}</div>\n  </section>`;\n}\n\nfunction renderOlderMissingPerson(item) {\n  const published = new Date(item.publishedAt || "");\n  const year = Number.isNaN(published.getTime()) ? "Äldre fall" : `Försvunnen sedan ${published.getFullYear()}`;\n  const place = item.originMunicipality || item.location || "närområdet";\n  return `<a class="missing-person-compact" href="${escapeAttribute(safeExternalUrl(item.url || MISSING_PEOPLE_SOURCE_URL))}" target="_blank" rel="noopener noreferrer">\n    <span class="missing-person-compact-icon"><i data-lucide="search"></i></span>\n    <span><strong>${escapeHtml(item.name || "Försvunnen person")}</strong><small>${escapeHtml(place)} · ${escapeHtml(year)}</small></span>\n    <span class="missing-person-compact-label">Äldre aktiv efterlysning</span>\n    <i data-lucide="arrow-up-right"></i>\n  </a>`;\n}\n\n'''

text = SCRIPT.read_text(encoding="utf-8")
if new not in text:
    if old not in text:
        raise SystemExit("Kunde inte hitta Missing People-renderingen att migrera")
    text = text.replace(old, new, 1)
if addition not in text:
    if anchor not in text:
        raise SystemExit("Kunde inte hitta renderMissingPerson")
    text = text.replace(anchor, addition + anchor, 1)
SCRIPT.write_text(text, encoding="utf-8")

css = '''\n<style>\n  .missing-people-older{grid-column:1/-1;margin-top:2px;padding:12px;background:#f8fafc;border:1px solid #e1e7ee;border-radius:13px}\n  .missing-people-older-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:8px;color:#5f6f82}\n  .missing-people-older-head>span{display:flex;align-items:center;gap:7px}.missing-people-older-head svg{width:15px}.missing-people-older-head strong{font-size:11px;color:#34445a}.missing-people-older-head small{font-size:9px}\n  .missing-people-older-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}\n  .missing-person-compact{display:grid;grid-template-columns:30px minmax(0,1fr) auto 14px;align-items:center;gap:8px;padding:9px 10px;background:#fff;border:1px solid #e4e9ef;border-radius:10px;transition:border-color .15s ease,box-shadow .15s ease,transform .15s ease}\n  .missing-person-compact:hover{border-color:#bdc9d6;box-shadow:0 5px 14px rgba(16,33,62,.06);transform:translateY(-1px)}\n  .missing-person-compact-icon{width:30px;height:30px;display:grid;place-items:center;color:#66788d;background:#eef2f6;border-radius:50%}.missing-person-compact-icon svg{width:15px}\n  .missing-person-compact>span:nth-child(2){display:grid;gap:2px;min-width:0}.missing-person-compact strong{font-size:11px;color:#26384f}.missing-person-compact small{font-size:9px;color:#7a8797}.missing-person-compact-label{padding:4px 7px;color:#75633c;background:#faf4e5;border-radius:999px;font-size:8px;font-weight:800;white-space:nowrap}.missing-person-compact>svg{width:13px;color:#77879a}\n  [data-theme="dark"] .missing-people-older{background:#102136;border-color:#31465e}[data-theme="dark"] .missing-person-compact{background:#0d1d31;border-color:#2c425a}[data-theme="dark"] .missing-person-compact strong{color:#e4edf7}[data-theme="dark"] .missing-person-compact-label{color:#dcc78e;background:#3b321e}\n  @media(max-width:760px){.missing-people-older-list{grid-template-columns:1fr}.missing-people-older-head{align-items:flex-start;flex-direction:column;gap:3px}.missing-person-compact{grid-template-columns:30px minmax(0,1fr) 14px}.missing-person-compact-label{grid-column:2/3;justify-self:start}.missing-person-compact>svg{grid-column:3;grid-row:1/3}}\n</style>\n'''
component = COMPONENT.read_text(encoding="utf-8")
if ".missing-people-older{" not in component:
    component += css
COMPONENT.write_text(component, encoding="utf-8")

print("Missing People: 1-årsgräns och kompakt äldre-visning applicerad")
