const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
async function run({paid=false,failed=false,expired=false}={}){
 const events=[];let extra;
 class E{constructor(){this.dataset={};this.children=[];this.hidden=true}append(...v){this.children.push(...v)}replaceChildren(...v){this.children=v}setAttribute(){}removeAttribute(){}addEventListener(){}after(v){extra=v}remove(){extra=null}closest(){return null}}
 const hosts=[1,2,3].map(()=>{const host=new E();host.section=new E();host.module=new E();host.querySelector=s=>s==='.premium-ads'?host.section:host.module;return host});
 const inventory=[1,2,3].flatMap(g=>Array.from({length:10},(_,i)=>({id:`P${g}-${String((g-1)*10+i+1).padStart(2,'0')}`,group:`premium-ad-${g}`,position:i+1})));
 const document={readyState:'loading',createElement:()=>new E(),addEventListener(){},querySelectorAll:()=>[],querySelector:s=>s.includes('data-component')?hosts[Number(s.match(/premium-ad-(\d)/)?.[1])-1]:s==='[data-test-preview-extra]'?extra:s==='[data-test-banner-preview]'?hosts.find(h=>h.section.dataset.testBannerPreview)?.section:null};
 const context={document,URL,URLSearchParams,console,queueMicrotask,location:{search:'?kommun=Åmål'},IntersectionObserver:class{observe(){}disconnect(){}},fetch:async u=>{if(u==='data/business-config.json')return {ok:true,json:async()=>({apiBase:'https://ads.test'})};if(u==='data/homepage-test-preview.json')return {ok:true,json:async()=>({enabled:true,expiresAt:expired?'2000-01-01T00:00:00Z':'2100-01-01T00:00:00Z',imageUrl:'assets/test.png'})};if(String(u).endsWith('/ads/events')){events.push(u);return {ok:true}};return {ok:!failed,json:async()=>({ok:true,banner:paid?{id:'customer',imageUrl:'/asset/customer',targetUrl:''}:null})}}};
 context.window=context;context.DINPULS_AD_INVENTORY=inventory;context.setTimeout=()=>{};context.setInterval=()=>{};context.clearInterval=()=>{};context.addEventListener=()=>{};
 vm.runInNewContext(fs.readFileSync('portal-ads.js','utf8'),context);await context.DinPulsAds.refreshHomepageAds();return {hosts,extra,events};
}
(async()=>{let r=await run();assert(r.hosts.every(h=>h.section.dataset.testBannerPreview));assert(r.extra);assert.equal(r.events.length,0,'Test previews must not inflate customer metrics');r=await run({paid:true});assert(r.hosts.every(h=>!h.section.dataset.testBannerPreview));assert(!r.extra,'Never add previews when all groups have customer advertisements');r=await run({failed:true});assert(r.hosts.every(h=>h.hidden));assert(!r.extra,'Network failures must not be treated as empty customer inventory');r=await run({expired:true});assert(r.hosts.every(h=>h.hidden));assert(!r.extra);console.log('PASS: four labelled previews, customer priority, no fake metrics, fail-closed inventory and expiry');})().catch(e=>{console.error(e);process.exitCode=1});
