const assert = require("node:assert/strict");
const fs = require("node:fs");
const data = JSON.parse(fs.readFileSync("data/practical.json", "utf8"));
const home = fs.readFileSync("components/primary-cards.html", "utf8");
const index = fs.readFileSync("index.html", "utf8");
const page = fs.readFileSync("praktiskt.html", "utf8");
const engine = fs.readFileSync("practical-engine.js", "utf8");
const ui = fs.readFileSync("practical-page.js", "utf8");
const css = fs.readFileSync("practical.css", "utf8");
assert(home.includes('id="praktiskt"') && home.includes('id="practical-page-link"'));
assert(index.includes("practical-engine.js"));
assert(engine.includes("encodeURIComponent(name)"));
assert.equal(Object.keys(data.municipalities).length, 1);
assert(data.municipalities.Åmål);
assert.equal(data.municipalities.Säffle, undefined);
const amal = data.municipalities.Åmål;
assert(amal.settlements.length >= 6 && amal.settlements[0].id === "all");
for (const type of ["map", "information", "hybrid"]) assert(amal.categories.some(x => x.presentationType === type));
assert(amal.places.every(x => x.primaryUrl && x.source && x.verifiedAt && x.coordinates.length === 2));
assert(amal.information.every(x => x.externalUrl && x.source && x.verifiedAt));
assert(page.includes('id="practical-settlement"') && page.includes('id="practical-category"'));
assert(page.includes('id="practical-flip"') && page.includes('id="practical-map"') && page.includes('id="practical-info"'));
assert(ui.includes('next==="information"') && ui.includes('if(next===currentSide)return'));
assert(ui.includes('p.categories.includes(category.id)') && ui.includes('p.settlement===settlement'));
assert(ui.includes('if(c.presentationType!=="information")renderMap(c)'));
assert(ui.includes("if(!record)") && ui.includes("Vi visar aldrig information från en annan kommun"));
assert(css.includes("prefers-reduced-motion:reduce") && css.includes("@media(max-width:760px)"));
console.log(`Praktiskt verifierat: ${amal.categories.length} kategorier, ${amal.places.length} platser, ${amal.information.length} informationsposter.`);
