/* Dedicated advanced bank for VDK Regelgenerator 2026.
   Advanced scenarios describe observable match events; the referee must make the classification. */
(() => {
"use strict";
const Q=[
{id:8001,c:"Avvaktande utvisning",level:"advanced",q:"Röd 14 ska utvisas. Blå har fortsatt kontroll över bollen och domarna avvaktar utvisningen. En passning från Blå 8 träffar Röd 14:s klubblad och studsar direkt tillbaka till Blå 8, som fortsätter anfallet. Vad gör domarna?",a:["Fortsätter avvakta utvisningen","Blåser när bollen träffar Röd 14:s klubblad","Avbryter och dömer tekning","Stryker utvisningen"],x:0,r:"Fortsätt avvakta.",e:"En beröring är inte samma sak som kontroll. Så länge felande lag inte får kontroll över bollen fortsätter den avvaktande utvisningen.",s:"Regel 602",t:"Skilj noga mellan beröring och kontroll."},
{id:8002,c:"Avvaktande utvisning",level:"advanced",q:"Röd har en avvaktande utvisning. Blå kontrollerar bollen. Blå 7 slår en passning bakåt som Röd 9 tar emot, får under kontroll och börjar föra framåt. När ska spelet stoppas?",a:["När Röd 9 får kontroll över bollen","När Blå 7 slår passningen","Först när Röd 9 passar eller skjuter","Spelet ska fortsätta tills bollen lämnar planen"],x:0,r:"När Röd får kontroll.",e:"Den avvaktande utvisningen verkställs när felande lag får kontroll över bollen.",s:"Regel 602",t:"Det avgörande är kontroll, inte vem som senast spelade bollen."},
{id:8003,c:"Straffslag",level:"advanced",q:"Blå 11 är fri centralt med bollen under kontroll och endast målvakten framför sig. Röd 4 kommer snett bakifrån och slår undan Blå 11:s klubba så att avslutet omöjliggörs. Vilken del av situationen är avgörande för valet mellan frislag och straffslag?",a:["Om förseelsen hindrar en klar målsituation","Om kontakten sker på offensiv planhalva","Om Röd 4 träffar bollen efteråt","Om Blå 11 faller till golvet"],x:0,r:"Bedöm den klara målsituationen.",e:"När en frislags- eller utvisningsbelagd förseelse hindrar en klar målsituation ska straffslagsbestämmelserna tillämpas.",s:"Regel 508",t:"Utgå från matchbilden före förseelsen, inte från hur dramatiskt spelaren faller."},
{id:8004,c:"Målvakt",level:"advanced",q:"Målvakten står med båda fötterna utanför målområdet och fångar bollen med händerna. Bollen befinner sig samtidigt helt innanför målområdets gräns. Vad ska domarna bedöma?",a:["Målvaktens position enligt regelns kriterier, inte bara bollens position","Endast bollens position","Endast var målvaktens händer befinner sig","Situationens utgång; räddning innebär alltid spela vidare"],x:0,r:"Målvaktens position måste bedömas.",e:"Målvaktens rättigheter är knutna till hur regelboken definierar målvaktens position. Bollens placering ensam avgör inte situationen.",s:"Regel 401 och målvaktsbestämmelserna",t:"Separera bollens position från spelarens regeltekniska position."},
{id:8005,c:"Målvakt",level:"advanced",q:"Blå 5 spelar avsiktligt bollen bakåt mot sin målvakt. Målvakten möter bollen utanför målområdet och spelar den vidare med foten utan att använda hand eller arm. Domslut?",a:["Spela vidare","Frislag för otillåtet tillbakaspel","Mindre lagstraff","Tekning"],x:0,r:"Spela vidare.",e:"Förbudet avser målvaktens mottagande med hand eller arm av en avsiktlig passning från medspelare. Att spela bollen med foten är inte samma förseelse.",s:"Regel 507.17",t:"Fråga exakt hur målvakten spelar bollen."},
{id:8006,c:"Målvaktsområdet",level:"advanced",q:"Vid ett inspel står en anfallare utanför målvaktsområdet men har klubbladet inne i området. Ingen kroppsdel rör golvet i området. Bollen spelas förbi spelaren utan kontakt. Domslut enbart på grund av spelarens position?",a:["Spela vidare","Frislag till försvarande lag","Mindre lagstraff","Tekning"],x:0,r:"Spela vidare.",e:"Klubban ensam innebär inte att utespelaren befinner sig i målvaktsområdet; en kroppsdel måste röra golvet där.",s:"Regel 507.8",t:"Linjerna tillhör området, men klubban behandlas annorlunda än kroppen."},
{id:8007,c:"Målvaktsområdet",level:"advanced",q:"En försvarare försöker täcka ett inspel och sätter ned ena knät på linjen till målvaktsområdet. Bollen är spelbar framför mål. Hur ska spelarens position bedömas?",a:["Spelaren befinner sig i målvaktsområdet","Spelaren är utanför eftersom endast linjen berörs","Spelaren är utanför om bollen inte är i området","Positionen saknar alltid regelbetydelse för försvarare"],x:0,r:"Spelaren befinner sig i målvaktsområdet.",e:"Linjen tillhör målvaktsområdet och en kroppsdel som rör golvet på linjen innebär att spelaren befinner sig i området.",s:"Regel 507.8",t:"Var exakt med linjens status."},
{id:8008,c:"Fördelsregel",level:"advanced",q:"Röd 8 hakas i mittzon men behåller full kontroll över bollen och får omedelbart ett numerärt två-mot-ett-läge framåt. Domaren bedömer att fortsatt spel ger Röd större fördel än ett frislag. Vad är korrekt?",a:["Tillämpa fördel och låt spelet fortsätta","Blås alltid direkt vid en frislagsbelagd förseelse","Låt spelet fortsätta endast om Röd gör mål","Döm tekning eftersom förseelsen redan skett"],x:0,r:"Tillämpa fördel.",e:"När icke felande lag behåller kontrollen och har större fördel av fortsatt spel kan fördelsregeln användas.",s:"Regel 506.1",t:"Bedöm den faktiska spelmässiga fördelen."},
{id:8009,c:"Fasta situationer",level:"advanced",q:"Ett inslag utförs ungefär en meter från korrekt plats. Bollen ligger still och ingen betydande fördel vinns. Domaren upptäcker placeringen direkt efter tillslaget. Vad är korrekt åtgärd?",a:["Gör om inslaget från korrekt plats","Frislag till motståndarna","Mindre lagstraff på utföraren","Låt alltid spelet fortsätta"],x:0,r:"Gör om inslaget.",e:"Felaktig placering utan ett uppenbart försök att vinna betydande fördel korrigeras genom att den fasta situationen görs om.",s:"Regel 507.15",t:"Skilj korrigering från ett avsiktligt betydande fördelsförsök."},
{id:8010,c:"Fasta situationer",level:"advanced",q:"Vid frislag placerar sig en motståndare först för nära bollen men börjar omedelbart backa undan. Utföraren slår frislaget snabbt innan motståndaren hunnit tre meter och bollen passerar utan att motståndaren ingriper. Vilken princip måste domaren framför allt bedöma?",a:["Om motståndaren faktiskt fördröjer eller påverkar frislaget","Att varje spelare inom tre meter automatiskt ska utvisas","Att frislaget alltid måste tas om","Att utförande lag förlorar frislaget när det slås snabbt"],x:0,r:"Bedöm om avståndsförseelsen faktiskt påverkar situationen.",e:"Avståndsregeln ska tillämpas tillsammans med händelseförloppet; domaren måste skilja aktivt hindrande från en spelare som omedelbart försöker inta korrekt avstånd.",s:"Regel 507 och utvisningsbestämmelserna",t:"Bedöm beteendet, inte en fryst ögonblicksbild."},
{id:8011,c:"Hög klubba",level:"advanced",q:"Blå 3 gör en skottfint. Klubban förs över midjehöjd nära ansiktet på Röd 12, som tvingas avbryta sitt försök att spela bollen för att undvika träff. Ingen fysisk kontakt sker. Vad är den centrala regelbedömningen?",a:["Om den höga svingen innebär risk för att motståndaren träffas","Att ingen kontakt skedde och spelet därför alltid fortsätter","Om bollen var över knähöjd","Om Röd 12 faktiskt tappar balansen"],x:0,r:"Risken för träff är central.",e:"Bestämmelsen om hög sving omfattar även skottfint. Fysisk träff är inte ett krav för att agerandet ska vara otillåtet.",s:"Regel 507.3",t:"Kontakt och risk är två olika saker."},
{id:8012,c:"Spel med kroppen",level:"advanced",q:"Röd 6 stoppar en boll med låret tydligt över knähöjd. Rörelsen är kontrollerad och ingen motståndare utsätts för fara. Vad döms?",a:["Spela vidare","Frislag för hög boll","Mindre lagstraff","Tekning"],x:0,r:"Spela vidare.",e:"Att stoppa bollen med låret räknas inte automatiskt som spel över knähöjd. En separat bedömning krävs om agerandet är farligt.",s:"Regel 507.4",t:"Kroppsdelens namn spelar roll i regeltexten."},
{id:8013,c:"Trängning",level:"advanced",q:"Två spelare springer sida vid sida mot en lös boll. Blå 9 flyttar sin löplinje och använder höften för att trycka Röd 5 åt sidan innan någon av dem når bollen. Kontakten är inte hård. Vad är den första regeltekniska frågan?",a:["Om trängningen sker på tillåtet sätt i kamp om bollen","Om kontakten är tillräckligt hård för utvisning","Om Blå 9 når bollen efter kontakten","Om Röd 5 faller"],x:0,r:"Bedöm om trängningen är tillåten.",e:"Tillåten kroppskontakt har tydliga förutsättningar. Att kontakten är lätt gör inte automatiskt en otillåten trängning tillåten.",s:"Regel 507.6",t:"Börja med typen av handling; bedöm därefter eventuell påföljdsnivå."},
{id:8014,c:"Målvaktsutkast",level:"advanced",q:"Målvakten kastar bollen långt. Bollen träffar sargen på egen planhalva och passerar därefter mittlinjen i luften utan ytterligare beröring. Domslut?",a:["Spela vidare","Frislag för felaktigt målvaktsutkast","Tekning på mittlinjen","Inslag vid mittlinjen"],x:0,r:"Spela vidare.",e:"Bollen får passera mittlinjen när den före dess passage har berört golv, sarg, spelare eller utrustning.",s:"Regel 507.14",t:"Identifiera om någon tillåten beröring sker före mittlinjen."},
{id:8015,c:"Målvaktsutkast",level:"advanced",q:"Målvakten kastar bollen. Den passerar mittlinjen i luften utan att dessförinnan ha berört golv, sarg, spelare eller utrustning. En medspelare tar emot bollen direkt på offensiv planhalva. Domslut?",a:["Frislag","Spela vidare eftersom en medspelare tar emot bollen","Tekning","Inslag"],x:0,r:"Frislag.",e:"Hela bollen får inte passera mittlinjen direkt från målvaktens kast eller spark utan föregående tillåten beröring.",s:"Regel 507.14",t:"Mottagningen efter mittlinjen reparerar inte ett redan felaktigt utkast."},
{id:8016,c:"Målvakt",level:"advanced",q:"Målvakten fångar bollen och lägger ned den efter två sekunder. Utan att någon annan spelare rör bollen tar målvakten omedelbart upp den igen med händerna. Hur ska kontrolltiden bedömas?",a:["Kontrollen fortsätter; nedläggningen nollställer inte automatiskt tiden","En ny tresekundersperiod börjar alltid","Målvakten får därefter hålla bollen obegränsat","Spelet stoppas för tekning direkt när bollen läggs ned"],x:0,r:"Kontrollen fortsätter.",e:"Att lägga ned och åter ta upp bollen bryter inte i sig målvaktens kontrolltid.",s:"Regel 507.16",t:"Titta på faktisk kontroll, inte bara handkontakt."},
{id:8017,c:"Spel utan klubba",level:"advanced",q:"Blå 4 tappar klubban i egen zon. Bollen rullar mot honom och han sparkar den en gång till en fri medspelare innan han hinner plocka upp klubban. Vilken regelmekanism måste domaren kontrollera innan domslutet bestäms?",a:["Vad regelboken tillåter en utespelare att göra utan klubba i den aktuella situationen","Om passningen når en medspelare","Om Blå 4 tappade klubban avsiktligt","Om motståndarna protesterar"],x:0,r:"Bedöm spel utan klubba enligt den aktuella bestämmelsen.",e:"Det avgörande är inte om aktionen lyckas utan om den handling spelaren utför utan klubba är tillåten enligt regelboken.",s:"Regel 605 och relevanta spelbestämmelser",t:"Separera orsaken till att klubban tappas från vad spelaren därefter gör."},
{id:8018,c:"Utvisningar",level:"advanced",q:"En spelare gör först en frislagsbelagd förseelse. Spelet fortsätter med fördel och samma spelare begår några sekunder senare en separat förseelse som ska leda till utvisning. Vad måste domaren göra i sin slutliga bedömning?",a:["Bedöma händelserna var för sig och verkställa den påföljd som följer av den senare förseelsen","Ignorera den senare förseelsen eftersom fördel redan tillämpats","Alltid lägga ihop båda handlingarna till matchstraff","Endast döma den första förseelsen"],x:0,r:"Bedöm de separata händelserna korrekt.",e:"Fördelsregeln gör inte en efterföljande separat utvisningsbelagd handling irrelevant. Händelseförloppet måste delas upp regeltekniskt.",s:"Regel 506 och 6 kap.",t:"Kronologi är ofta viktigare än den mest spektakulära kontakten."},
{id:8019,c:"Mål",level:"advanced",q:"Ett skott är på väg mot mål när slutsignalen ljuder. Bollen har ännu inte helt passerat mållinjen när signalen börjar ljuda och går därefter in. Vad är den centrala bedömningen?",a:["Om bollen helt passerade mållinjen innan speltiden upphörde","Om skottet avlossades före signalen","Om målvakten hann reagera","Om domaren såg bollen lämna klubban"],x:0,r:"Tidpunkten då bollen helt passerar mållinjen är avgörande.",e:"Att skottet avlossats före slutsignalen innebär inte i sig att ett senare mål kan godkännas.",s:"Regel 2 och målbestämmelserna",t:"Skottögonblick och målögonblick är inte samma sak."},
{id:8020,c:"Mål",level:"advanced",q:"Bollen går mot en tom målbur. En försvarare begår en regelstridig handling som hindrar att bollen går i mål. Vilken särskild fråga måste domaren pröva utöver själva grundförseelsen?",a:["Om förutsättningarna för straffslag eller tilldömt mål är uppfyllda","Om anfallande lag vill ha frislag i stället","Om försvararen tidigare varit utvisad","Om bollen hade hög fart"],x:0,r:"Pröva mål- och straffslagsbestämmelserna.",e:"När en regelstridig handling påverkar en klar målsituation mot tom målbur kan följden gå längre än grundförseelsens vanliga återstart.",s:"Regel 508 och målbestämmelserna",t:"Stanna inte vid grundförseelsen när en målsituation påverkas."},
{id:8021,c:"Straffslagsavgörande",level:"advanced",q:"Efter de fem inledande straffslagen för vardera laget är ställningen fortfarande lika. Lag Blå vill använda samma behöriga utespelare till de tre följande straffslagen. Är det tillåtet enligt 2026 års regler?",a:["Ja","Nej, alla fem måste användas igen innan någon får slå på nytt","Nej, samma spelare får bara slå vartannat straffslag","Ja, men bara om motståndarlaget använder samma upplägg"],x:0,r:"Ja.",e:"Efter de fem inledande straffslagen får laget välja skytt fritt bland behöriga utespelare; samma spelare kan användas upprepade gånger.",s:"Regel 204.1",t:"Blanda inte ihop 2026 års regel med den äldre rotationsbestämmelsen."},
{id:8022,c:"Straffslagsavgörande",level:"advanced",q:"Inför de fem första straffslagen frågar sekretariatet domaren efter en skriftlig lista med fem skyttar i bestämd ordning. Vad gäller enligt 2026 års regelverk?",a:["Något sådant krav på förhandsnotering ska inte läggas till om det inte följer av den aktuella regeln","Listan är obligatorisk och ordningen får aldrig ändras","Endast hemmalaget behöver lämna lista","Listan krävs bara i slutspel"],x:0,r:"Tillämpa 2026 års regel utan den gamla listregeln.",e:"Den äldre hanteringen med noterade skyttar och rotationsbegränsning ska inte föras över till 2026 års regelverk.",s:"Regel 204.1",t:"Det här är en medveten kontroll av gammal regelkunskap."},
{id:8023,c:"Påföljdsbedömning",level:"advanced",q:"En spelare kommer sent in i en närkamp och träffar motståndaren med en handling som domarna efter helhetsbedömning klassificerar som vårdslös. Vilken påföljdsnivå hör till den klassificeringen?",a:["Större lagstraff","Mindre lagstraff","Endast frislag","Grovt matchstraff"],x:0,r:"Större lagstraff.",e:"I 2026 års terminologi kopplas vårdslöst agerande till större lagstraff. Klassificeringen ska inte blandas ihop med oaktsamt agerande.",s:"Regel 6 kap. – påföljdsnivåer",t:"Oaktsam och vårdslös är regeltermer, inte synonymer."},
{id:8024,c:"Påföljdsbedömning",level:"advanced",q:"Domarna bedömer en fysisk handling som oaktsam men inte vårdslös, våldsam eller brutal. Vilken nivå ska domarna utgå från när handlingen är utvisningsbelagd?",a:["Mindre lagstraff","Större lagstraff","Lindrigt matchstraff","Grovt matchstraff"],x:0,r:"Mindre lagstraff.",e:"Oaktsamt agerande ligger på nivån mindre lagstraff i 2026 års påföljdssystem.",s:"Regel 6 kap. – påföljdsnivåer",t:"Använd exakt regelterminologi."},
{id:8025,c:"Påföljdsbedömning",level:"advanced",q:"En situation innehåller hård kroppskontakt. Domarna måste avgöra om handlingen är oaktsam, vårdslös, våldsam eller brutal. Vilket arbetssätt är regeltekniskt bäst?",a:["Klassificera själva handlingen och välj därefter den påföljd som hör till nivån","Utgå från om den träffade spelaren ligger kvar länge","Ge alltid större lagstraff vid hård kontakt","Låt matchens betydelse avgöra påföljden"],x:0,r:"Klassificera handlingen först.",e:"Påföljden ska följa den regeltekniska klassificeringen av handlingen. Skadeutfall eller matchens betydelse ersätter inte den bedömningen.",s:"Regel 6 kap. – påföljdsnivåer",t:"Handling först, påföljd därefter."},
{id:8026,c:"Fasthållning",level:"advanced",q:"Röd 10 för handen mot Blå 3:s klubba och för undan den utan att greppa. Röd 10 vinner därmed bollen. Vilken grundförseelse ska domaren identifiera innan eventuell högre påföljdsnivå bedöms?",a:["Fasthållning/otillåten påverkan på motståndarens klubba","Hög klubba","Felaktig trängning","Spel utan klubba"],x:0,r:"Identifiera fasthållningsförseelsen.",e:"Att med arm eller hand föra undan motståndarens klubba omfattas av fasthållningsbestämmelsen. Därefter bedöms om omständigheterna höjer påföljden.",s:"Regel 507.2",t:"Identifiera först grundförseelsen, sedan konsekvensen."},
{id:8027,c:"Fasta situationer",level:"advanced",q:"Bollen träffar domaren, ändrar riktning tydligt och skapar omedelbart ett friläge för ett lag som annars inte hade haft bollen. Hur återupptas spelet efter avblåsningen?",a:["Tekning","Frislag till laget som missgynnades","Inslag till laget som senast hade kontroll","Spelet får aldrig stoppas efter domarträff"],x:0,r:"Tekning.",e:"När en domarträff märkbart påverkar spelet behandlas situationen som en onaturlig situation och spelet återupptas med tekning.",s:"Regel 503.6",t:"Domarträff i sig räcker inte; påverkan på spelet är avgörande."},
{id:8028,c:"Fasta situationer",level:"advanced",q:"Två motståndare begår samtidigt varsin frislagsbelagd förseelse i en duell och domarna kan inte fastställa någon riktning på den fasta situationen. Vad döms?",a:["Tekning","Frislag till laget som senast hade bollen","Ett frislag åt vardera håll","Mindre lagstraff på båda"],x:0,r:"Tekning.",e:"När motståndare samtidigt begår frislagsbelagda förseelser och riktningen inte kan avgöras återupptas spelet med tekning.",s:"Regel 503.9",t:"Samtidighet och avsaknad av riktning är nyckeln."},
{id:8029,c:"Frislag",level:"advanced",q:"Ett frislag nära målvaktsområdet ska placeras. Anfallande lag ställer sig så att försvarande lag inte kan inta sin tillåtna murposition direkt utanför området. Vilket lag har gjort den första regelstridiga handlingen i den beskrivna situationen?",a:["Anfallande lag","Försvarande lag","Båda lagen automatiskt","Inget lag; domaren måste alltid vänta tills muren är klar"],x:0,r:"Anfallande lag.",e:"Anfallarna får inte förhindra eller försvåra för försvararna att ställa upp muren. Det betyder inte att anfallarna måste vänta på en färdig mur när de i övrigt kan utföra frislaget korrekt.",s:"Regel 506.2 och 507.7",t:"Skilj rätten att slå snabbt från rätten att hindra motståndarnas placering."},
{id:8030,c:"Matchledning",level:"advanced",q:"Domaren har tillämpat fördel efter en förseelse. Icke felande lag behåller bollen men väljer därefter frivilligt en säker bakåtpassning i stället för den möjliga anfallsvägen. Vilken princip är viktigast när domaren utvärderar den tidigare fördelen?",a:["Fördelen bedöms utifrån situationen när beslutet fattas, inte utifrån att laget senare väljer ett annat spelalternativ","Domaren måste alltid gå tillbaka och döma frislaget","Varje bakåtpassning upphäver automatiskt fördelen","Fördel får bara användas om ett avslut följer"],x:0,r:"Bedöm fördelen vid beslutstillfället.",e:"Fördelsbedömningen handlar om om fortsatt spel gav laget en större faktisk möjlighet än den fasta situationen. Lagets senare taktiska val gör inte automatiskt den ursprungliga bedömningen felaktig.",s:"Regel 506.1",t:"Skilj domarens fördelsbedömning från lagets efterföljande beslut."}
];
const base=Array.isArray(window.VDK_QUESTIONS)?window.VDK_QUESTIONS:[];
window.VDK_QUESTIONS=[...base.filter(q=>q.level!=="advanced"),...Q];
window.VDK_ADVANCED_QUESTIONS=Q;
})();
