(() => {
  "use strict";
  const Q = window.VDK_QUESTIONS || [];
  const STATS_KEY = "vdk-regelgenerator-stats-v1";
  const THEME_KEY = "vdk-regelgenerator-theme";
  const VARIANT_COUNT = 3;
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  let setupMode = "training", session = [], index = 0, score = 0, answers = [], currentSetup = null;

  function stats(){try{return JSON.parse(localStorage.getItem(STATS_KEY)||'{"answered":0,"correct":0,"categories":{}}')}catch{return {answered:0,correct:0,categories:{}}}}
  function saveStats(result){const st=stats();st.rules??={};result.forEach(({q,ok})=>{st.answered++;if(ok)st.correct++;st.categories[q.c]??={answered:0,correct:0};st.categories[q.c].answered++;if(ok)st.categories[q.c].correct++;const key=String(q.baseId??q.id);st.rules[key]??={answered:0,correct:0,variants:{}};st.rules[key].answered++;if(ok)st.rules[key].correct++;st.rules[key].variants[q.variant??0]??={answered:0,correct:0};st.rules[key].variants[q.variant??0].answered++;if(ok)st.rules[key].variants[q.variant??0].correct++});localStorage.setItem(STATS_KEY,JSON.stringify(st));updateDashboard()}
  function updateDashboard(){const st=stats(),pct=st.answered?Math.round(st.correct/st.answered*100):null;$("#accuracy-value").textContent=pct===null?"–":pct+"%";$("#questions-answered").textContent=`${st.answered} frågor besvarade`;$("#progress-copy").textContent=st.answered?`${st.correct} korrekta svar. Fortsätt där precisionen är lägst.`:"Gör ditt första pass för att börja följa utvecklingen.";$("#bank-count").textContent=Q.length;$("#reset-stats").disabled=!st.answered}
  function resetStats(){const st=stats();if(!st.answered)return;if(!confirm(`Nollställa all din statistik från ${st.answered} besvarade frågor? Detta går inte att ångra.`))return;localStorage.removeItem(STATS_KEY);updateDashboard();$("#progress-copy").textContent="Statistiken är nollställd. Ditt nästa pass blir en ny start."}
  function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function variantText(q,variant){if(variant===1)return `På planen uppstår följande situation: ${q.q} Vilket alternativ följer regelboken?`;if(variant===2)return `Curve ball – skilj avgörande fakta från sådant som kan vilseleda: ${q.q} Vad gäller?`;return q.q}
  function variantUsage(q,variant){return stats().rules?.[String(q.id)]?.variants?.[variant]?.answered||0}
  function chooseVariant(q,cycle=0){const variants=[0,1,2].map(v=>({v,used:variantUsage(q,v)}));const least=Math.min(...variants.map(v=>v.used));const available=variants.filter(v=>v.used===least).map(v=>v.v);return available[cycle%available.length]}
  function withShuffledAnswers(q,variant=0){const choices=q.a.map((text,i)=>({text,correct:i===q.x}));return {...q,baseId:q.id,variant,displayId:`${q.id}-${variant}`,q:variantText(q,variant),choices:shuffle(choices)}}
  function weakProfile(){const st=stats(),categories=Object.entries(st.categories||{}).filter(([,v])=>v.answered).sort((a,b)=>a[1].correct/a[1].answered-b[1].correct/b[1].answered),weakCategories=categories.filter(([,v])=>v.correct/v.answered<.75).map(([c])=>c),missedRules=Object.entries(st.rules||{}).filter(([,v])=>v.correct<v.answered).map(([id])=>Number(id));const accuracy=st.answered?st.correct/st.answered:0;return {st,weakCategories,missedRules,high:st.answered>=20&&(accuracy>=.88||missedRules.length<=2)}}
  function weightedWeakPool(){const profile=weakProfile(),missed=new Set(profile.missedRules),weak=new Set(profile.weakCategories),focus=shuffle(Q.filter(q=>missed.has(q.id)||weak.has(q.c))),general=shuffle(Q.filter(q=>!missed.has(q.id)&&!weak.has(q.c)));if(!focus.length)return shuffle(Q);if(profile.high){const mixed=[];while(focus.length||general.length){if(focus.length)mixed.push(focus.shift());for(let i=0;i<2&&general.length;i++)mixed.push(general.shift())}return mixed}return [...focus,...general]}
  function poolFor(mode,category){let pool=mode==="new"?Q.filter(q=>q.n):mode==="weak"?weightedWeakPool():[...Q];if(category&&category!=="all")pool=pool.filter(q=>q.c===category);return pool.length?pool:[...Q]}
  function buildSession(mode,count,category){const pool=mode==="weak"?poolFor(mode,category):shuffle(poolFor(mode,category)),out=[];for(let cycle=0;out.length<count;cycle++){const round=cycle?shuffle(pool):pool;for(const q of round){if(out.length>=count)break;out.push(withShuffledAnswers(q,chooseVariant(q,cycle)))}}return out}
  function categories(){return [...new Set(Q.map(q=>q.c))].sort((a,b)=>a.localeCompare(b,"sv"))}
  function openSetup(mode){setupMode=mode;const exam=mode==="exam",fresh=mode==="new",weak=mode==="weak",profile=weak?weakProfile():null;$("#setup-kicker").textContent=exam?"DOMARPROV":fresh?"NYA REGLER 2026":weak?"SMART REPETITION":"SNABBTRÄNING";$("#setup-title").textContent=exam?"Bygg ditt domarprov":fresh?"Träna förändringarna":weak&&profile.high?"Fånga de sista luckorna":weak?"Slipa på svagheterna":"Ställ in ditt pass";$("#setup-copy").textContent=exam?"Facit och analys visas när hela provet är klart.":weak&&profile.high?"Du ligger på en hög nivå. Därför blandar vi hela regelbanken och väger in reglerna du senast missade – utan repetitiva frågor.":weak?"Passet prioriterar dina svagaste områden men visar varje grundregel högst en gång.":"Du får facit, förklaring och regelkälla direkt efter varje svar.";const counts=exam?[25,50,100]:[10,25,50];$("#count-options").innerHTML=counts.map((n,i)=>`<label class="choice"><input type="radio" name="count" value="${n}" ${i===0?'checked':''}><span>${n} frågor</span></label>`).join("");$("#category-field").hidden=fresh||weak;$("#category-options").innerHTML=["all",...categories()].map((c,i)=>`<label class="choice"><input type="radio" name="category" value="${c}" ${i===0?'checked':''}><span>${c==="all"?"Blandade regler":c}</span></label>`).join("");$("#setup-dialog").showModal()}
  function begin(){const count=Number(document.querySelector('input[name="count"]:checked').value),category=document.querySelector('input[name="category"]:checked')?.value||"all";currentSetup={mode:setupMode,count,category};session=buildSession(setupMode,count,category);index=0;score=0;answers=[];$("#setup-dialog").close();showOnly("session");renderQuestion()}
  function showOnly(view){$("#session-view").hidden=view!=="session";$("#result-view").hidden=view!=="result";$("#library-view").hidden=view!=="library";$$('body>main,body>footer,.topbar').forEach(el=>el.hidden=view!=="home");window.scrollTo(0,0)}
  function modeName(){return {training:"SNABBTRÄNING",new:"NYA REGLER",exam:"DOMARPROV",weak:"SVAGA OMRÅDEN"}[currentSetup.mode]}
  function renderQuestion(){const q=session[index];$("#session-mode").textContent=modeName();$("#progress-label").textContent=`${index+1} / ${session.length}`;$("#progress-bar").style.width=`${index/session.length*100}%`;$("#live-score").textContent=`${score} rätt`;$("#question-category").textContent=q.c;$("#question-rule").textContent=q.s;$("#question-text").textContent=q.q;$("#question-tip").textContent=q.t;$("#feedback").hidden=true;$("#answers").innerHTML=q.choices.map((o,i)=>`<button class="answer" data-index="${i}"><i>${i+1}</i><span>${o.text}</span></button>`).join("");$$('.answer').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.index))))}
  function answer(choiceIndex){if(answers[index])return;const q=session[index],chosen=q.choices[choiceIndex],ok=chosen.correct;if(ok)score++;answers[index]={q,ok,choiceIndex};$$('.answer').forEach((b,i)=>{b.disabled=true;if(q.choices[i].correct)b.classList.add('correct');else if(i===choiceIndex)b.classList.add('wrong')});$("#live-score").textContent=`${score} rätt`;if(currentSetup.mode!=="exam")showFeedback(q,ok);else setTimeout(next,280)}
  function showFeedback(q,ok){const f=$("#feedback");f.hidden=false;f.dataset.correct=String(ok);$("#feedback-icon").textContent=ok?"✓":"×";$("#feedback-title").textContent=ok?"Korrekt bedömt":"Inte riktigt";$("#feedback-ruling").textContent=q.r;$("#feedback-explanation").textContent=q.e;$("#feedback-source").textContent=`${q.s} · Regelhandbok 2026`;$("#next-question").textContent=index===session.length-1?"Visa resultat →":"Nästa fråga →";f.scrollIntoView({behavior:"smooth",block:"nearest"})}
  function next(){if(!answers[index])return;if(index<session.length-1){index++;renderQuestion()}else finish()}
  function finish(){saveStats(answers);showOnly("result");const pct=Math.round(score/session.length*100);$("#result-percent").textContent=pct+"%";$("#result-fraction").textContent=`${score} av ${session.length} rätt`;$("#result-title").textContent=pct>=90?"Matchklar!":pct>=75?"Stabil nivå":pct>=60?"På rätt väg":"Dags för en ny period";$("#result-message").textContent=pct>=90?"Mycket stark regelträff. Fortsätt med svaga områden för att hålla nivån.":"Gå igenom områdena nedan och kör ett nytt fokuserat pass.";const grouped={};answers.forEach(a=>{grouped[a.q.c]??={n:0,c:0};grouped[a.q.c].n++;if(a.ok)grouped[a.q.c].c++});$("#result-breakdown").innerHTML=Object.entries(grouped).sort((a,b)=>a[1].c/a[1].n-b[1].c/b[1].n).map(([c,v])=>`<div class="breakdown-row"><strong>${c}</strong><span>${v.c} / ${v.n} rätt</span></div>`).join("")}
  function renderLibrary(){const term=$("#rule-search").value.trim().toLocaleLowerCase("sv"),cat=$("#rule-filter").value;const rows=Q.filter(q=>(cat==="all"||q.c===cat)&&(`${q.q} ${q.r} ${q.e} ${q.s}`.toLocaleLowerCase("sv").includes(term)));$("#library-list").innerHTML=rows.length?rows.map(q=>`<article class="rule-item"><header><span>${q.c}</span><span>${q.n?'NY 2026':'REGEL 2026'}</span></header><h3>${q.q}</h3><p><strong>${q.r}</strong> ${q.e}</p><footer>${q.s}</footer></article>`).join(""):"<p>Inga regler matchade sökningen.</p>"}
  function openLibrary(){showOnly("library");$("#rule-filter").innerHTML='<option value="all">Alla områden</option>'+categories().map(c=>`<option>${c}</option>`).join('');renderLibrary()}
  function init(){if(localStorage.getItem(THEME_KEY)==="dark")document.body.classList.add("dark");updateDashboard();$$('[data-start-mode]').forEach(b=>b.addEventListener('click',()=>openSetup(b.dataset.startMode)));$("#weak-mode").addEventListener('click',()=>openSetup('weak'));$("#reset-stats").addEventListener('click',resetStats);$("#begin-session").addEventListener('click',e=>{e.preventDefault();begin()});$("#next-question").addEventListener('click',next);$("#quit-session").addEventListener('click',()=>{if(confirm("Avsluta pågående pass?"))showOnly("home")});$("#retry-session").addEventListener('click',()=>{session=buildSession(currentSetup.mode,currentSetup.count,currentSetup.category);index=score=0;answers=[];showOnly("session");renderQuestion()});$("#back-home").addEventListener('click',()=>showOnly("home"));$("#open-library").addEventListener('click',openLibrary);$("#close-library").addEventListener('click',()=>showOnly("home"));$("#rule-search").addEventListener('input',renderLibrary);$("#rule-filter").addEventListener('change',renderLibrary);$("#theme-toggle").addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem(THEME_KEY,document.body.classList.contains('dark')?'dark':'light')});document.addEventListener('keydown',e=>{if(!$("#session-view").hidden){if(/^[1-4]$/.test(e.key)&&!answers[index])$("#answers").children[Number(e.key)-1]?.click();if(e.key==='Enter'&&answers[index]&&currentSetup.mode!=="exam")next()}})}
  init();
})();
