(() => {
  "use strict";
  const Q = window.VDK_QUESTIONS || [];
  const STATS_KEY = "vdk-regelgenerator-stats-v1";
  const THEME_KEY = "vdk-regelgenerator-theme";
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  let setupMode = "training", session = [], index = 0, score = 0, answers = [], currentSetup = null;

  function stats(){try{return JSON.parse(localStorage.getItem(STATS_KEY)||'{"answered":0,"correct":0,"categories":{}}')}catch{return {answered:0,correct:0,categories:{}}}}
  function saveStats(result){const st=stats();result.forEach(({q,ok})=>{st.answered++;if(ok)st.correct++;st.categories[q.c]??={answered:0,correct:0};st.categories[q.c].answered++;if(ok)st.categories[q.c].correct++});localStorage.setItem(STATS_KEY,JSON.stringify(st));updateDashboard()}
  function updateDashboard(){const st=stats(),pct=st.answered?Math.round(st.correct/st.answered*100):null;$("#accuracy-value").textContent=pct===null?"–":pct+"%";$("#questions-answered").textContent=`${st.answered} frågor besvarade`;$("#progress-copy").textContent=st.answered?`${st.correct} korrekta svar. Fortsätt där precisionen är lägst.`:"Gör ditt första pass för att börja följa utvecklingen.";$("#bank-count").textContent=Q.length}
  function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function withShuffledAnswers(q,variant=0){const choices=q.a.map((text,i)=>({text,correct:i===q.x}));return {...q,displayId:`${q.id}-${variant}`,q:variant?`Ny bedömning: ${q.q}`:q.q,choices:shuffle(choices)}}
  function poolFor(mode,category){let pool=mode==="new"?Q.filter(q=>q.n):[...Q];if(category&&category!=="all")pool=pool.filter(q=>q.c===category);if(mode==="weak"){const st=stats();const weak=Object.entries(st.categories||{}).filter(([,v])=>v.answered&&v.correct/v.answered<.75).map(([k])=>k);if(weak.length)pool=Q.filter(q=>weak.includes(q.c))}return pool.length?pool:[...Q]}
  function buildSession(mode,count,category){const pool=shuffle(poolFor(mode,category));const out=[];for(let i=0;i<count;i++)out.push(withShuffledAnswers(pool[i%pool.length],Math.floor(i/pool.length)));return out}
  function categories(){return [...new Set(Q.map(q=>q.c))].sort((a,b)=>a.localeCompare(b,"sv"))}
  function openSetup(mode){setupMode=mode;const exam=mode==="exam",fresh=mode==="new",weak=mode==="weak";$("#setup-kicker").textContent=exam?"DOMARPROV":fresh?"NYA REGLER 2026":weak?"SVAGA OMRÅDEN":"SNABBTRÄNING";$("#setup-title").textContent=exam?"Bygg ditt domarprov":fresh?"Träna förändringarna":weak?"Slipa på svagheterna":"Ställ in ditt pass";$("#setup-copy").textContent=exam?"Facit och analys visas när hela provet är klart.":"Du får facit, förklaring och regelkälla direkt efter varje svar.";const counts=exam?[25,50,100]:[10,25,50];$("#count-options").innerHTML=counts.map((n,i)=>`<label class="choice"><input type="radio" name="count" value="${n}" ${i===0?'checked':''}><span>${n} frågor</span></label>`).join("");$("#category-field").hidden=fresh||weak;$("#category-options").innerHTML=["all",...categories()].map((c,i)=>`<label class="choice"><input type="radio" name="category" value="${c}" ${i===0?'checked':''}><span>${c==="all"?"Blandade regler":c}</span></label>`).join("");$("#setup-dialog").showModal()}
  function begin(){const count=Number(document.querySelector('input[name="count"]:checked').value),category=document.querySelector('input[name="category"]:checked')?.value||"all";currentSetup={mode:setupMode,count,category};session=buildSession(setupMode,count,category);index=0;score=0;answers=[];$("#setup-dialog").close();showOnly("session");renderQuestion()}
  function showOnly(view){$("#session-view").hidden=view!=="session";$("#result-view").hidden=view!=="result";$("#library-view").hidden=view!=="library";$$('body>main,body>footer,.topbar').forEach(el=>el.hidden=view!=="home");window.scrollTo(0,0)}
  function modeName(){return {training:"SNABBTRÄNING",new:"NYA REGLER",exam:"DOMARPROV",weak:"SVAGA OMRÅDEN"}[currentSetup.mode]}
  function renderQuestion(){const q=session[index];$("#session-mode").textContent=modeName();$("#progress-label").textContent=`${index+1} / ${session.length}`;$("#progress-bar").style.width=`${index/session.length*100}%`;$("#live-score").textContent=`${score} rätt`;$("#question-category").textContent=q.c;$("#question-rule").textContent=q.s;$("#question-text").textContent=q.q;$("#question-tip").textContent=q.t;$("#feedback").hidden=true;$("#answers").innerHTML=q.choices.map((o,i)=>`<button class="answer" data-index="${i}"><i>${i+1}</i><span>${o.text}</span></button>`).join("");$$('.answer').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.index))))}
  function answer(choiceIndex){if(answers[index])return;const q=session[index],chosen=q.choices[choiceIndex],ok=chosen.correct;if(ok)score++;answers[index]={q,ok,choiceIndex};$$('.answer').forEach((b,i)=>{b.disabled=true;if(q.choices[i].correct)b.classList.add('correct');else if(i===choiceIndex)b.classList.add('wrong')});$("#live-score").textContent=`${score} rätt`;if(currentSetup.mode!=="exam")showFeedback(q,ok);else setTimeout(next,280)}
  function showFeedback(q,ok){const f=$("#feedback");f.hidden=false;f.dataset.correct=String(ok);$("#feedback-icon").textContent=ok?"✓":"×";$("#feedback-title").textContent=ok?"Korrekt bedömt":"Inte riktigt";$("#feedback-ruling").textContent=q.r;$("#feedback-explanation").textContent=q.e;$("#feedback-source").textContent=`${q.s} · Regelhandbok 2026`;$("#next-question").textContent=index===session.length-1?"Visa resultat →":"Nästa fråga →";f.scrollIntoView({behavior:"smooth",block:"nearest"})}
  function next(){if(!answers[index])return;if(index<session.length-1){index++;renderQuestion()}else finish()}
  function finish(){saveStats(answers);showOnly("result");const pct=Math.round(score/session.length*100);$("#result-percent").textContent=pct+"%";$("#result-fraction").textContent=`${score} av ${session.length} rätt`;$("#result-title").textContent=pct>=90?"Matchklar!":pct>=75?"Stabil nivå":pct>=60?"På rätt väg":"Dags för en ny period";$("#result-message").textContent=pct>=90?"Mycket stark regelträff. Fortsätt med svaga områden för att hålla nivån.":"Gå igenom områdena nedan och kör ett nytt fokuserat pass.";const grouped={};answers.forEach(a=>{grouped[a.q.c]??={n:0,c:0};grouped[a.q.c].n++;if(a.ok)grouped[a.q.c].c++});$("#result-breakdown").innerHTML=Object.entries(grouped).sort((a,b)=>a[1].c/a[1].n-b[1].c/b[1].n).map(([c,v])=>`<div class="breakdown-row"><strong>${c}</strong><span>${v.c} / ${v.n} rätt</span></div>`).join("")}
  function renderLibrary(){const term=$("#rule-search").value.trim().toLocaleLowerCase("sv"),cat=$("#rule-filter").value;const rows=Q.filter(q=>(cat==="all"||q.c===cat)&&(`${q.q} ${q.r} ${q.e} ${q.s}`.toLocaleLowerCase("sv").includes(term)));$("#library-list").innerHTML=rows.length?rows.map(q=>`<article class="rule-item"><header><span>${q.c}</span><span>${q.n?'NY 2026':'REGEL 2026'}</span></header><h3>${q.q}</h3><p><strong>${q.r}</strong> ${q.e}</p><footer>${q.s}</footer></article>`).join(""):"<p>Inga regler matchade sökningen.</p>"}
  function openLibrary(){showOnly("library");$("#rule-filter").innerHTML='<option value="all">Alla områden</option>'+categories().map(c=>`<option>${c}</option>`).join('');renderLibrary()}
  function init(){if(localStorage.getItem(THEME_KEY)==="dark")document.body.classList.add("dark");updateDashboard();$$('[data-start-mode]').forEach(b=>b.addEventListener('click',()=>openSetup(b.dataset.startMode)));$("#weak-mode").addEventListener('click',()=>openSetup('weak'));$("#begin-session").addEventListener('click',e=>{e.preventDefault();begin()});$("#next-question").addEventListener('click',next);$("#quit-session").addEventListener('click',()=>{if(confirm("Avsluta pågående pass?"))showOnly("home")});$("#retry-session").addEventListener('click',()=>{session=buildSession(currentSetup.mode,currentSetup.count,currentSetup.category);index=score=0;answers=[];showOnly("session");renderQuestion()});$("#back-home").addEventListener('click',()=>showOnly("home"));$("#open-library").addEventListener('click',openLibrary);$("#close-library").addEventListener('click',()=>showOnly("home"));$("#rule-search").addEventListener('input',renderLibrary);$("#rule-filter").addEventListener('change',renderLibrary);$("#theme-toggle").addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem(THEME_KEY,document.body.classList.contains('dark')?'dark':'light')});document.addEventListener('keydown',e=>{if(!$("#session-view").hidden){if(/^[1-4]$/.test(e.key)&&!answers[index])$("#answers").children[Number(e.key)-1]?.click();if(e.key==='Enter'&&answers[index]&&currentSetup.mode!=="exam")next()}})}
  init();
})();
