(() => {
  "use strict";
  const bank = window.VDK_QUESTIONS;
  if (!Array.isArray(bank)) return;

  // Death Mode: endast 2026-regler. Långa sekvenser, flera regelmoment och ett entydigt facit.
  const death = [
    {id:9001,level:"death",c:"Death Mode",n:true,q:"Blå 7 tappar klubban i en närkamp och går direkt mot byteszonen för att byta. Blå 11 har samtidigt kontrollerad boll på offensiv planhalva. Domaren har identifierat att Blå 7 genom själva bytet efter tappad klubba gör sig skyldig till mindre lagstraff. Blå 11 passar bakåt, bollen går utan beröring in i Blås eget tomma mål. Vad blir den fullständiga hanteringen?",a:["Avvakta utvisningen, godkänn självmålet och verkställ därefter den mindre utvisningen","Blås direkt när Blå 7 börjar byta och döm frislag; målet kan därför inte uppstå","Godkänn självmålet och stryk den mindre utvisningen eftersom mål gjorts","Underkänn målet eftersom felande lag hade kontroll när den avvaktande utvisningen började"],x:0,r:"Självmålet godkänns och den avvaktande mindre utvisningen verkställs.",e:"Spelaren som tappat klubban och byter omfattas av mindre lagstraff. Utvisningen avvaktas medan icke felande lag kan fortsätta anfalla; ett självmål under den avvaktande situationen godkänns men stryker inte utvisningen.",s:"Regel 602, 605 och 702",t:"Tre steg: identifiera U2, hantera avvaktningen och skilj självmål från mål av icke felande lag."},
    {id:9002,level:"death",c:"Death Mode",n:true,q:"Röd 4 har båda knäna i golvet och spelar bollen med klubban precis när Blå 9 annars skulle komma ensam med målvakten. Domarna bedömer att handlingen är en frislag-/utvisningsbelagd förseelse och att den direkt hindrar en klar målsituation. Vilket återupptagande har företräde?",a:["Straffslag, eftersom förseelsen hindrar en klar målsituation; eventuell utvisning hanteras dessutom enligt den regel som förseelsen faller under","Mindre lagstraff och frislag, eftersom liggande spel alltid stannar på U2-nivå","Endast frislag, eftersom bollen spelas med klubban","Större lagstraff och tekning"],x:0,r:"Straffslag.",e:"Det avgörande är inte bara grundförseelsen liggande spel utan konsekvensen: en frislag-/utvisningsbelagd förseelse som hindrar en klar målsituation leder till straffslag. Påföljden för själva förseelsen bedöms separat.",s:"Regel 507/605 samt 510",t:"Death Mode-fällan är att stanna vid grundförseelsens normala påföljd och missa att den hindrar en klar målsituation."},
    {id:9003,level:"death",c:"Death Mode",n:true,q:"Röd har en avvaktande mindre utvisning. Blå anfaller med kontroll. Röd 8 bryter en passning men bollen studsar omedelbart från hans klubba tillbaka till Blå utan att Röd får kontrollerad kontroll. Blå gör mål i samma anfall. Vad är den centrala bedömningen?",a:["Avgör om Röd faktiskt fick sådan kontroll över bollen att den avvaktande utvisningen skulle verkställas; en ren okontrollerad beröring är inte automatiskt samma sak som kontrollerad kontroll","Spelet måste alltid stoppas vid minsta beröring av felande lag","Målet ska alltid underkännas när felande lag har rört bollen","Den avvaktande utvisningen stryks redan när Röd 8 träffar bollen"],x:0,r:"Kontrollbegreppet avgör.",e:"I en avvaktande utvisning måste domaren skilja en okontrollerad beröring från att felande lag kontrollerar/spelar bollen på det sätt som verkställer utvisningen. Det är den exakta bollkontrollen som avgör om anfallet får fortsätta.",s:"Regel 602",t:"Det här är en sekvensfråga: beröring, kontroll och mål är inte synonymer."},
    {id:9004,level:"death",c:"Death Mode",n:true,q:"En medspelare passar avsiktligt tillbaka bollen mot sin målvakt. Målvakten lämnar målområdet helt, stoppar bollen med foten utanför området, bollen rullar tillbaka in i målområdet och målvakten följer efter och tar upp den med händerna. Ingen annan rör bollen. Domslut?",a:["Spela vidare","Frislag för passning till målvakten","Mindre lagstraff för målvakten","Straffslag eftersom bollen tas med händerna efter en avsiktlig passning"],x:0,r:"Spela vidare.",e:"2026-regeln gör den fullständiga positionen vid mottagningen avgörande. När målvakten helt har lämnat målområdet och stoppar passningen där får målvakten därefter återvända och ta upp samma boll i målområdet.",s:"Regel 303 och 507.17",t:"Fällan är att bara se den sista handberöringen och glömma var målvakten tog emot passningen."},
    {id:9005,level:"death",c:"Death Mode",n:true,q:"Blå får frislag rakt framför mål. När frislaget slås står Röd 6 med båda fötterna utanför målvaktsområdet men har ett knä i golvet på målvaktsområdets linje. Röd 6 rör aldrig bollen. Skottet räddas av målvakten. Vilket domslut följer av spelarens placering vid det direkta frislaget mot mål?",a:["Straffslag","Spela vidare eftersom Röd 6 inte rörde bollen","Nytt frislag men ingen möjlighet till straffslag","Mindre lagstraff är den enda möjliga påföljden"],x:0,r:"Straffslag.",e:"Linjen tillhör området. Vid den särskilda frislagssituationen direkt mot mål är försvarande utespelares placering i målvaktsområdet avgörande; bollkontakt krävs inte för att situationen ska bedömas enligt straffslagsregeln.",s:"Regel 507.8 och 510",t:"Två detaljer konkurrerar: ingen bollkontakt, men knät på linjen placerar spelaren i området."},
    {id:9006,level:"death",c:"Death Mode",n:true,q:"Blå spelar utan målvakt. Röd 10 är ensam med den tomma målburens öppna målsituation när Blå 3 begår en förseelse som enligt regel 510 ska leda till straffslag. Bollen går inte i mål. Vad ska domarna döma enligt 2026-regeln?",a:["Tilldömt mål till Röd; målet ersätter straffslaget","Straffslag mot tom målbur","Straffslag och därefter tilldömt mål om straffen missas","Frislag eftersom det inte finns någon målvakt att slå straff mot"],x:0,r:"Tilldömt mål.",e:"När försvarande lag har ersatt målvakten med utespelare och begår en förseelse som leder till straffslag tilldelas icke felande lag mål enligt den särskilda 2026-regeln.",s:"Regel 510 och 701.3",t:"Det intuitiva svaret 'straff mot tom bur' är inte regelns lösning."},
    {id:9007,level:"death",c:"Death Mode",n:true,q:"Efter fem inledande straffslag per lag är straffslagsavgörandet fortfarande oavgjort. Röd låter samma utespelare slå lagets första, andra och tredje extra straffslag. Ingen annan omständighet gör spelaren obehörig. Vad gäller enligt Regelhandbok 2026?",a:["Det är tillåtet; efter de fem inledande straffarna får laget välja utespelare fritt och samma spelare kan slå de extra straffarna upprepade gånger","Spelaren får slå två extra straffar men inte ett tredje innan övriga noterade spelare slagit två","Alla fem ursprungliga skyttar måste slå en extra straff innan någon får slå igen","De fem ursprungliga skyttarna måste fortsätta i samma ordning"],x:0,r:"Tillåtet.",e:"Den gamla rotationsbegränsningen och kravet på noterad fortsättningsordning ska inte användas som facit i 2026-regeln. Efter de fem inledande straffarna kan laget välja skytt fritt bland behöriga utespelare och samma spelare kan användas igen.",s:"Regel 204.1, Regelhandbok 2026",t:"Det här testar aktivt att domaren inte faller tillbaka på den gamla regeln."},
    {id:9008,level:"death",c:"Death Mode",n:true,q:"Målvakten kastar bollen från målområdet. Bollen passerar mittlinjen i luften utan att före mittlinjen röra golv, sarg, spelare eller utrustning. På andra planhalvan träffar den en försvarare och går därefter i mål. Vad döms?",a:["Frislag för felaktigt utkast; den senare beröringen och målet reparerar inte överträdelsen som redan skett när hela bollen passerade mittlinjen direkt","Mål eftersom en försvarare rörde bollen innan den gick i mål","Mål eftersom målvaktskast får resultera i mål 2026","Tekning eftersom både felaktigt utkast och mål inträffar"],x:0,r:"Frislag för felaktigt utkast.",e:"Målvaktskast kan leda till mål, men utkastet måste först vara korrekt. Överträdelsen är fullbordad när hela bollen passerar mittlinjen utan föregående tillåten beröring; en senare beröring på andra planhalvan ändrar inte det.",s:"Regel 507.14 och 702",t:"Två korrekta regler krockar skenbart. Tidsordningen avgör vilken som får effekt."},
    {id:9009,level:"death",c:"Death Mode",n:true,q:"Blå 8 gör sig skyldig till en förseelse som domarna bedömer som vårdslös och som ska ge mindre lagstraff. Domarna avvaktar eftersom Röd har kontroll och en klar offensiv möjlighet. Innan spelet stoppas begår Blå 12 en separat våldsam förseelse mot en annan Röd spelare. Vilken princip måste domarna följa när spelet stoppas?",a:["De två förseelserna ska bedömas separat på sina respektive nivåer; den senare våldsamma förseelsen raderar inte den tidigare vårdslösa","Endast den grövsta förseelsen ska bestraffas","Båda spelarna ska automatiskt få samma straff eftersom förseelserna sker under samma avvaktning","Den första utvisningen upphör när en grövre förseelse inträffar"],x:0,r:"Förseelserna hanteras separat.",e:"Avvaktning innebär inte att en redan identifierad förseelse försvinner när ytterligare en förseelse sker. Domaren måste hålla isär spelare, handlingar och nivåerna vårdslös respektive våldsam och därefter tillämpa respektive regelpåföljd.",s:"Regel 602 samt relevanta bestämmelser om vårdslösa och våldsamma förseelser",t:"Death Mode handlar här om sekvensminne: två gärningar, två spelare och två olika nivåbedömningar."},
    {id:9010,level:"death",c:"Death Mode",n:true,q:"Ett skott lämnar Röd 9:s klubba en bråkdel av en sekund före slutsignalen. När signalen börjar ljuda är en del av bollen över mållinjen men hela bollen har ännu inte passerat. Resten av bollen passerar linjen medan signalen ljuder. Samtidigt har Blå målvakt redan lämnat planen för en extra utespelare. Domslut?",a:["Inte mål; hela bollen måste ha passerat mållinjen innan slutsignalen börjar ljuda","Mål eftersom skottet lämnade klubban före signalen","Mål eftersom någon del av bollen var över linjen före signalen","Tilldömt mål eftersom Blå saknade målvakt"],x:0,r:"Inte mål.",e:"Match-/periodslutet bestäms av när slutsignalen börjar ljuda och mål kräver att hela bollen har passerat mållinjen. Att målvakten är uttagen förändrar inte dessa två krav.",s:"Regel 201.1 och 703",t:"Irrelevant information om uttagen målvakt ska sorteras bort; millisekunden och hela bollens position är det som avgör."}
  ];

  const ids = new Set(death.map(q => q.id));
  for (let i = bank.length - 1; i >= 0; i--) if (ids.has(bank[i].id)) bank.splice(i, 1);
  death.forEach(q => bank.push(q));
})();
