(() => {
  "use strict";
  const bank = window.VDK_QUESTIONS;
  if (!Array.isArray(bank)) return;
  const death = [
    {id:9001,level:"death",c:"Death Mode",n:true,q:"Blå 7 tappar klubban i en närkamp och börjar omedelbart byta genom att fortsätta mot den egna byteszonen utan att röra bollen eller en motståndare. Blå behåller kontroll över bollen. Vad ska domarna göra?",a:["Avvakta mindre lagstraff mot Blå 7; när Blå kontrollerar bollen verkställs utvisningen och spelet återupptas enligt reglerna för avvaktande utvisning","Spela vidare eftersom Blå 7 inte rör bollen","Frislag utan utvisning","Blås direkt och döm tekning"],x:0,r:"Avvaktande mindre lagstraff.",e:"605 anger att deltagande utan klubba ger mindre lagstraff och räknar uttryckligen in när en spelare som tappat klubban byter. Eftersom Blå fortfarande kontrollerar bollen avvaktas utvisningen enligt 602.",s:"Regel 605 (spel utan klubba) och 602.1–2",t:"Curve ball: 'han deltar inte i spelet' räddar inte spelaren när regeltexten uttryckligen räknar själva bytet efter tappad klubba."},
    {id:9002,level:"death",c:"Death Mode",n:true,q:"Röd har en avvaktande mindre utvisning. Blå kontrollerar bollen men slår en felpassning bakåt som går direkt in i Blås eget tomma mål utan att Röd rör bollen. Vad blir domslutet?",a:["Målet godkänns som självmål och den avvaktande utvisningen verkställs","Målet underkänns eftersom en avvaktande utvisning pågår","Målet godkänns och den avvaktande mindre utvisningen stryks","Tekning utan mål och utan utvisning"],x:0,r:"Självmålet godkänns och utvisningen verkställs.",e:"602 skiljer mellan korrekt mål av icke felande lag, som kan stryka den sist utdömda avvaktande mindre utvisningen, och självmål av icke felande lag, som ska godkännas. Självmålet stryker inte den avvaktande utvisningen.",s:"Regel 602.2 och 702.1",t:"Death Mode: skilj 'gör mål' från 'gör självmål'."},
    {id:9003,level:"death",c:"Death Mode",n:true,q:"Röd har en avvaktande utvisning. Blå kontrollerar bollen och anfaller. Röd bryter sedan passningen och får tydlig, kontrollerad kontroll över bollen. Var ska spelet återupptas efter att utvisningen verkställts?",a:["Med inslag till Blå på närmaste tekningspunkt i förhållande till bollens läge vid avblåsningen","Med frislag där den ursprungliga utvisningsförseelsen skedde","Med tekning på mittpunkten","Med inslag exakt där Röd tog bollen"],x:0,r:"Inslag på närmaste tekningspunkt.",e:"När avvaktande utvisning verkställs därför att felande lag kontrollerar eller spelar bollen kontrollerat ska spelet återupptas med inslag till icke felande lag på närmaste tekningspunkt i förhållande till bollens läge.",s:"Regel 602.2 och 505",t:"Den gamla reflexen 'frislag där förseelsen skedde' är fällan."},
    {id:9004,level:"death",c:"Death Mode",n:true,q:"Målvakten står med vänster fot på målområdets linje och höger fot utanför området. En medspelare spelar avsiktligt tillbaka bollen. Målvakten stoppar först bollen med foten och tar därefter upp den med händerna utan att först helt lämna målområdet. Domslut?",a:["Frislag för passning till målvakten","Spela vidare eftersom första beröringen sker med foten","Mindre lagstraff","Straffslag"],x:0,r:"Frislag.",e:"Linjen tillhör målområdet, så målvakten har inte helt lämnat det. Vid mottagning av en avsiktlig passning räknas hand-/armberöring som mottagning även efter att målvakten först stoppat bollen med annan kroppsdel.",s:"Regel 303.2 och 507.17",t:"Death Mode: fotberöringen först gör inte den efterföljande handberöringen laglig."},
    {id:9005,level:"death",c:"Death Mode",n:true,q:"Målvakten lämnar först målområdet helt, stoppar en avsiktlig passning från en medspelare med foten, går därefter tillbaka in i målområdet och tar upp samma boll med händerna. Ingen annan spelare rör bollen. Domslut?",a:["Spela vidare","Frislag för passning till målvakten","Mindre lagstraff","Straffslag"],x:0,r:"Spela vidare.",e:"507.17 anger uttryckligen att målvakten efter att helt ha lämnat målområdet och stoppat bollen får återvända till målområdet och ta upp den utan att detta räknas som passning till målvakten.",s:"Regel 303.2 och 507.17",t:"Det avgörande är att målvakten var helt utanför målområdet när passningen togs emot och bollen stoppades."},
    {id:9006,level:"death",c:"Death Mode",n:true,q:"Blå 9 skjuter ett frislag direkt mot mål. Röd 4 har båda fötterna utanför målvaktsområdet men ett knä i golvet på målvaktsområdets linje när skottet går. Bollen räddas av målvakten. Vad döms?",a:["Straffslag","Frislag till Blå","Spela vidare eftersom Röd 4 inte rör bollen","Mindre lagstraff utan straffslag"],x:0,r:"Straffslag.",e:"Linjen tillhör målvaktsområdet och en kroppsdel i golvet där innebär att utespelaren befinner sig i området. Vid frislag direkt mot mål ska straffslag alltid dömas om en försvarande utespelare befinner sig i målvaktsområdet.",s:"Regel 507.8 och 510.1",t:"Bollkontakt krävs inte. Placeringen när frislaget går direkt mot mål är fällan."},
    {id:9007,level:"death",c:"Death Mode",n:true,q:"Blå 5 spelar bollen med båda knäna i golvet och hindrar därmed Röd från att få ett friläge. Domarna bedömer att Blå vinner betydande fördel genom handlingen. Vilken påföljd är utgångspunkten?",a:["Mindre lagstraff för liggande spel","Endast frislag eftersom båda knäna alltid är frislagsnivå","Större lagstraff","Spela vidare eftersom bollen spelas med klubban"],x:0,r:"Mindre lagstraff.",e:"507.22 omfattar försök att spela bollen med båda knäna i golvet. När en utespelare liggande eller sittande stoppar eller spelar bollen för att vinna betydande fördel höjs handlingen till mindre lagstraff enligt 605.",s:"Regel 507.22 och 605 (liggande spel för betydande fördel)",t:"Death Mode: samma kroppsställning kan ligga på olika nivå beroende på konsekvensen."},
    {id:9008,level:"death",c:"Death Mode",n:true,q:"En Röd avbytare som inte håller på att byta står med ena foten ovanpå sargen. Samtidigt pågår spelet långt från byteszonen och avbytaren påverkar inte bollen eller någon spelare. Vad döms?",a:["Mindre lagstraff för för många spelare","Ingen åtgärd eftersom spelet inte påverkas","Frislag först om spelaren rör bollen","Muntlig tillsägelse är enda möjliga åtgärd"],x:0,r:"Mindre lagstraff.",e:"605 anger uttryckligen att en spelare i byteszonen eller på utvisningsbänken som står med foten på sargen, eller annars passerar sargens vertikalplan med kropp eller utrustning, räknas som för många spelare oavsett spelpåverkan.",s:"Regel 605 (för många spelare)",t:"Death Mode: 'långt från spelet' är irrelevant information."},
    {id:9009,level:"death",c:"Death Mode",n:true,q:"I ett straffslagsavgörande har ett lag angett fem ordinarie skyttar skriftligen i bestämd ordning. Efter de fem straffarna är matchen fortfarande oavgjord. Samma spelare slår lagets första och andra extra straff. Är det tillåtet?",a:["Ja, extra straffar får slås av vilken utespelare som helst och samma spelare får slå flera, med begränsningen att ingen får slå sitt tredje innan övriga noterade spelare slagit minst två","Nej, alla fem måste slå exakt en extra straff var innan någon får slå igen","Ja, utan någon ytterligare begränsning","Nej, de fem ordinarie skyttarna måste fortsätta i exakt samma ordning"],x:0,r:"Ja, men regeln innehåller en rotationsbegränsning.",e:"Efter de fem inledande straffarna får extra straffar slås av vilken utespelare som helst och samma spelare får slå flera. En spelare får dock inte slå sitt tredje straffslag förrän övriga noterade spelare i laget slagit minst två, och så vidare.",s:"Regel 204.1",t:"Death Mode: både friheten och rotationsspärren måste finnas med i svaret."},
    {id:9010,level:"death",c:"Death Mode",n:true,q:"Blå spelar utan målvakt. Röd 8 är fri mot det tomma målet när Blå 4 begår en förseelse som enligt 510 ska leda till straffslag. Vad blir konsekvensen enligt 2026 års regel?",a:["Mål tilldöms Röd och ersätter straffslaget","Straffslag ska ändå utföras mot tom målbur","Mål plus straffslag","Endast frislag eftersom målvakt saknas"],x:0,r:"Mål tilldöms.",e:"När försvarande målvakt har ersatts av en utespelare och försvarande lag begår en förseelse som leder till straffslag ska mål tilldömas. Målet ersätter straffslaget och krediteras den spelare i icke felande lag som senast rörde bollen.",s:"Regel 701.3 och 510",t:"Death Mode: domaren dömer inte ett symboliskt straffslag mot tom bur; regeln tilldelar mål."}
  ];
  const ids = new Set(death.map(q=>q.id));
  for (let i=bank.length-1;i>=0;i--) if (ids.has(bank[i].id)) bank.splice(i,1);
  death.forEach(q=>bank.push(q));
})();